sonar.organization=o11y
sonar.projectKey=O11y_o11y

# relative paths to source directories. More details and properties are described
# in https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/
sonar.sources=./src