// Code generated by zipdoc; DO NOT EDIT.
//
// The access face's slice of the package extraction, split into its own file
// so concurrent slices do not contend on zipdoc_gen.go; a later `go generate
// -run zipdoc ./` folds every slice back into zipdoc_gen.go, at which point
// this file is deleted.

package o11y

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/o11y/roles/:id", zip.Doc{
		Description: "Deletes a custom role. A role that still has user or\nservice-account assignees, or an auth-domain mapping, is refused; managed\nroles cannot be deleted.",
	})
	zip.Describe("DELETE /v1/o11y/service_accounts/:id", zip.Doc{
		Description: "Deletes a service account and revokes every key it\nholds.",
	})
	zip.Describe("DELETE /v1/o11y/service_accounts/:id/keys/:fid", zip.Doc{
		Description: "Revokes an API key. Revocation is immediate and\npermanent.",
	})
	zip.Describe("DELETE /v1/o11y/service_accounts/:id/roles/:rid", zip.Doc{
		Description: "Removes a role from a service account.",
	})
	zip.Describe("GET /v1/o11y/roles", zip.Doc{
		Description: "Lists every role in the caller's org — the managed ones the\nplatform seeds and the custom ones its admins created.",
		Fields: map[string]string{
			"O11yRole.createdAt":   "CreatedAt is when the role was created.",
			"O11yRole.description": "Description says what the role is for.",
			"O11yRole.id":          "ID is the role id.",
			"O11yRole.name":        "Name is the role's name.",
			"O11yRole.orgId":       "OrgID is the org the role belongs to.",
			"O11yRole.type":        "Type is custom or managed.",
			"O11yRole.updatedAt":   "UpdatedAt is when it last changed.",
			"O11yRolesOut.data":    "Data holds the roles.",
			"O11yRolesOut.status":  "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/roles/:id", zip.Doc{
		Description: "Returns one role with the transaction groups it grants.",
		Fields: map[string]string{
			"O11yObjectGroup.resource":         "Resource is the objects' type and kind.",
			"O11yObjectGroup.selectors":        "Selectors pick the instances; a wildcard selects them all.",
			"O11yResourceRef.kind":             "Kind is the resource kind the type belongs to.",
			"O11yResourceRef.type":             "Type is the resource type, e.g. role, dashboard, serviceaccount.",
			"O11yRoleDetail.createdAt":         "CreatedAt is when the role was created.",
			"O11yRoleDetail.description":       "Description says what the role is for.",
			"O11yRoleDetail.id":                "ID is the role id.",
			"O11yRoleDetail.name":              "Name is the role's name.",
			"O11yRoleDetail.orgId":             "OrgID is the org the role belongs to.",
			"O11yRoleDetail.transactionGroups": "TransactionGroups are the grants the role carries.",
			"O11yRoleDetail.type":              "Type is custom or managed.",
			"O11yRoleDetail.updatedAt":         "UpdatedAt is when it last changed.",
			"O11yRoleOut.data":                 "Data holds the role and its transaction groups.",
			"O11yRoleOut.status":               "Status is \"success\".",
			"O11yTransactionGroup.objectGroup": "ObjectGroup is the set of objects it allows the verb on.",
			"O11yTransactionGroup.relation":    "Relation is the verb the grant allows.",
		},
	})
	zip.Describe("GET /v1/o11y/service_accounts", zip.Doc{
		Description: "Lists the caller's org's service accounts.",
		Fields: map[string]string{
			"O11yServiceAccount.createdAt":  "CreatedAt is when the account was created.",
			"O11yServiceAccount.email":      "Email is the address the account authenticates as.",
			"O11yServiceAccount.id":         "ID is the service account id.",
			"O11yServiceAccount.name":       "Name is the account's name.",
			"O11yServiceAccount.orgId":      "OrgID is the org the account belongs to.",
			"O11yServiceAccount.status":     "Status is active or deleted.",
			"O11yServiceAccount.updatedAt":  "UpdatedAt is when it last changed.",
			"O11yServiceAccountsOut.data":   "Data holds the service accounts.",
			"O11yServiceAccountsOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/service_accounts/:id", zip.Doc{
		Description: "Returns one service account with the roles it holds.",
		Fields: map[string]string{
			"O11yRole.createdAt":                           "CreatedAt is when the role was created.",
			"O11yRole.description":                         "Description says what the role is for.",
			"O11yRole.id":                                  "ID is the role id.",
			"O11yRole.name":                                "Name is the role's name.",
			"O11yRole.orgId":                               "OrgID is the org the role belongs to.",
			"O11yRole.type":                                "Type is custom or managed.",
			"O11yRole.updatedAt":                           "UpdatedAt is when it last changed.",
			"O11yServiceAccountDetail.createdAt":           "CreatedAt is when the account was created.",
			"O11yServiceAccountDetail.email":               "Email is the address the account authenticates as.",
			"O11yServiceAccountDetail.id":                  "ID is the service account id.",
			"O11yServiceAccountDetail.name":                "Name is the account's name.",
			"O11yServiceAccountDetail.orgId":               "OrgID is the org the account belongs to.",
			"O11yServiceAccountDetail.serviceAccountRoles": "ServiceAccountRoles are the account's role assignments.",
			"O11yServiceAccountDetail.status":              "Status is active or deleted.",
			"O11yServiceAccountDetail.updatedAt":           "UpdatedAt is when it last changed.",
			"O11yServiceAccountOut.data":                   "Data holds the account and its role assignments.",
			"O11yServiceAccountOut.status":                 "Status is \"success\".",
			"O11yServiceAccountRole.createdAt":             "CreatedAt is when the role was assigned.",
			"O11yServiceAccountRole.id":                    "ID is the assignment's own id.",
			"O11yServiceAccountRole.role":                  "Role is the role itself.",
			"O11yServiceAccountRole.roleId":                "RoleID is the role held.",
			"O11yServiceAccountRole.serviceAccountId":      "ServiceAccountID is the account holding the role.",
			"O11yServiceAccountRole.updatedAt":             "UpdatedAt is when the assignment last changed.",
		},
	})
	zip.Describe("GET /v1/o11y/service_accounts/:id/keys", zip.Doc{
		Description: "Lists a service account's API keys — metadata only,\nnever the secrets.",
		Fields: map[string]string{
			"O11yAPIKey.createdAt":        "CreatedAt is when the key was minted.",
			"O11yAPIKey.expiresAt":        "ExpiresAt is when the key stops working, as a unix timestamp in seconds;\nzero means never.",
			"O11yAPIKey.id":               "ID is the key id.",
			"O11yAPIKey.lastObservedAt":   "LastObservedAt is when the key was last seen authenticating.",
			"O11yAPIKey.name":             "Name is the key's name.",
			"O11yAPIKey.serviceAccountId": "ServiceAccountID is the account the key belongs to.",
			"O11yAPIKey.updatedAt":        "UpdatedAt is when it last changed.",
			"O11yAPIKeysOut.data":         "Data holds the keys.",
			"O11yAPIKeysOut.status":       "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/service_accounts/:id/roles", zip.Doc{
		Description: "Lists the roles a service account holds.",
		Fields: map[string]string{
			"O11yRole.createdAt":                "CreatedAt is when the role was created.",
			"O11yRole.description":              "Description says what the role is for.",
			"O11yRole.id":                       "ID is the role id.",
			"O11yRole.name":                     "Name is the role's name.",
			"O11yRole.orgId":                    "OrgID is the org the role belongs to.",
			"O11yRole.type":                     "Type is custom or managed.",
			"O11yRole.updatedAt":                "UpdatedAt is when it last changed.",
			"O11yServiceAccountRolesOut.data":   "Data holds the roles.",
			"O11yServiceAccountRolesOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/service_accounts/me", zip.Doc{
		Description: "Returns the calling service account itself, with the\nroles it holds — the self-inspection read for a key-authenticated caller.",
		Fields: map[string]string{
			"O11yRole.createdAt":                           "CreatedAt is when the role was created.",
			"O11yRole.description":                         "Description says what the role is for.",
			"O11yRole.id":                                  "ID is the role id.",
			"O11yRole.name":                                "Name is the role's name.",
			"O11yRole.orgId":                               "OrgID is the org the role belongs to.",
			"O11yRole.type":                                "Type is custom or managed.",
			"O11yRole.updatedAt":                           "UpdatedAt is when it last changed.",
			"O11yServiceAccountDetail.createdAt":           "CreatedAt is when the account was created.",
			"O11yServiceAccountDetail.email":               "Email is the address the account authenticates as.",
			"O11yServiceAccountDetail.id":                  "ID is the service account id.",
			"O11yServiceAccountDetail.name":                "Name is the account's name.",
			"O11yServiceAccountDetail.orgId":               "OrgID is the org the account belongs to.",
			"O11yServiceAccountDetail.serviceAccountRoles": "ServiceAccountRoles are the account's role assignments.",
			"O11yServiceAccountDetail.status":              "Status is active or deleted.",
			"O11yServiceAccountDetail.updatedAt":           "UpdatedAt is when it last changed.",
			"O11yServiceAccountOut.data":                   "Data holds the account and its role assignments.",
			"O11yServiceAccountOut.status":                 "Status is \"success\".",
			"O11yServiceAccountRole.createdAt":             "CreatedAt is when the role was assigned.",
			"O11yServiceAccountRole.id":                    "ID is the assignment's own id.",
			"O11yServiceAccountRole.role":                  "Role is the role itself.",
			"O11yServiceAccountRole.roleId":                "RoleID is the role held.",
			"O11yServiceAccountRole.serviceAccountId":      "ServiceAccountID is the account holding the role.",
			"O11yServiceAccountRole.updatedAt":             "UpdatedAt is when the assignment last changed.",
		},
	})
	zip.Describe("POST /v1/o11y/authz/check", zip.Doc{
		Description: "Evaluates a batch of transactions — relation plus object — for\nthe authenticated caller and answers each with its authorization verdict, in\nthe order they were asked. It is the read a UI uses to decide which controls\nto show.",
		Fields: map[string]string{
			"O11yCheckOut.data":                "Data holds the verdicts.",
			"O11yCheckOut.status":              "Status is \"success\".",
			"O11yObject.resource":              "Resource is the resource's type and kind.",
			"O11yObject.selector":              "Selector picks the instance — an FGA object string, wildcard allowed.",
			"O11yResourceRef.kind":             "Kind is the resource kind the type belongs to.",
			"O11yResourceRef.type":             "Type is the resource type, e.g. role, dashboard, serviceaccount.",
			"O11yTransaction.object":           "Object is the resource the verb would act on.",
			"O11yTransaction.relation":         "Relation is the verb being asked about, e.g. read, create, update, delete.",
			"O11yTransactionResult.authorized": "Authorized says whether the caller may do it.",
			"O11yTransactionResult.object":     "Object is the resource it would act on.",
			"O11yTransactionResult.relation":   "Relation is the verb that was asked about.",
		},
	})
	zip.Describe("POST /v1/o11y/roles", zip.Doc{
		Description: "Creates a custom role in the caller's org from a name, an optional\ndescription and the transaction groups it grants, answering the new role's id.\n\nNames are lowercase letters and hyphens only, and may not start with the\nreserved managed-role prefix; the runtime refuses anything else.",
		Fields: map[string]string{
			"O11yCreated.id":                     "ID is the new record's id.",
			"O11yObjectGroup.resource":           "Resource is the objects' type and kind.",
			"O11yObjectGroup.selectors":          "Selectors pick the instances; a wildcard selects them all.",
			"O11yResourceRef.kind":               "Kind is the resource kind the type belongs to.",
			"O11yResourceRef.type":               "Type is the resource type, e.g. role, dashboard, serviceaccount.",
			"O11yRoleCreateIn.description":       "Description says what the role is for.",
			"O11yRoleCreateIn.name":              "Name is the role's name: lowercase letters and hyphens, at most 50\ncharacters, not starting with the reserved managed-role prefix. Required.",
			"O11yRoleCreateIn.transactionGroups": "TransactionGroups are the grants the role carries.",
			"O11yRoleCreateOut.data":             "Data carries the new role's id.",
			"O11yRoleCreateOut.status":           "Status is \"success\".",
			"O11yTransactionGroup.objectGroup":   "ObjectGroup is the set of objects it allows the verb on.",
			"O11yTransactionGroup.relation":      "Relation is the verb the grant allows.",
		},
	})
	zip.Describe("POST /v1/o11y/service_accounts", zip.Doc{
		Description: "Creates a service account in the caller's org,\nanswering its id. The name — a lowercase letter followed by lowercase\nletters, digits or hyphens — becomes the account's email local part.",
		Fields: map[string]string{
			"O11yCreated.id":                     "ID is the new record's id.",
			"O11yServiceAccountCreateIn.name":    "Name is the account's name: a lowercase letter followed by lowercase\nletters, digits or hyphens, at most 50 characters. Required.",
			"O11yServiceAccountCreateOut.data":   "Data carries the new account's id.",
			"O11yServiceAccountCreateOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/service_accounts/:id/keys", zip.Doc{
		Description: "Mints an API key for a service account and answers\nthe key's id and its secret — the one time the secret is ever shown.\n\nExpiresAt is a unix timestamp in seconds; zero means the key never expires,\nand a timestamp in the past is refused.",
		Fields: map[string]string{
			"O11yAPIKeyCreateIn.expiresAt": "ExpiresAt is when the key stops working, as a unix timestamp in seconds.\nZero means it never expires; a past timestamp is refused.",
			"O11yAPIKeyCreateIn.name":      "Name is the key's name: a lowercase letter followed by lowercase letters,\ndigits or hyphens, at most 80 characters. Required.",
			"O11yAPIKeyCreateOut.data":     "Data carries the key's id and secret.",
			"O11yAPIKeyCreateOut.status":   "Status is \"success\".",
			"O11yAPIKeySecret.id":          "ID is the key id.",
			"O11yAPIKeySecret.key":         "Key is the secret the service account authenticates with.",
		},
	})
	zip.Describe("POST /v1/o11y/service_accounts/:id/roles", zip.Doc{
		Description: "Assigns a role, named by its id, to a service\naccount.",
		Fields: map[string]string{
			"O11yServiceAccountRoleGrantIn.id": "RoleID is the id of the role to assign. Required.",
		},
	})
	zip.Describe("PUT /v1/o11y/roles/:id", zip.Doc{
		Description: "Replaces a custom role's description and transaction groups.\nBoth fields are mandatory — send an empty string or an empty array to clear\none — and managed roles cannot be edited.",
		Fields: map[string]string{
			"O11yObjectGroup.resource":           "Resource is the objects' type and kind.",
			"O11yObjectGroup.selectors":          "Selectors pick the instances; a wildcard selects them all.",
			"O11yResourceRef.kind":               "Kind is the resource kind the type belongs to.",
			"O11yResourceRef.type":               "Type is the resource type, e.g. role, dashboard, serviceaccount.",
			"O11yRoleUpdateIn.description":       "Description says what the role is for. Required — send an empty string to\nclear it.",
			"O11yRoleUpdateIn.transactionGroups": "TransactionGroups are the grants the role carries. Required — send an\nempty array to clear them.",
			"O11yTransactionGroup.objectGroup":   "ObjectGroup is the set of objects it allows the verb on.",
			"O11yTransactionGroup.relation":      "Relation is the verb the grant allows.",
		},
	})
	zip.Describe("PUT /v1/o11y/service_accounts/:id", zip.Doc{
		Description: "Renames a service account.",
		Fields: map[string]string{
			"O11yServiceAccountUpdateIn.name": "Name is the account's new name, under the same rules it was created with.\nRequired.",
		},
	})
	zip.Describe("PUT /v1/o11y/service_accounts/:id/keys/:fid", zip.Doc{
		Description: "Renames an API key or moves its expiry.",
		Fields: map[string]string{
			"O11yAPIKeyUpdateIn.expiresAt": "ExpiresAt is when the key stops working, as a unix timestamp in seconds.\nZero means it never expires; a past timestamp is refused.",
			"O11yAPIKeyUpdateIn.name":      "Name is the key's new name, under the same rules it was created with.\nRequired.",
		},
	})
	zip.Describe("PUT /v1/o11y/service_accounts/me", zip.Doc{
		Description: "Renames the calling service account.",
		Fields: map[string]string{
			"O11yMyServiceAccountUpdateIn.name": "Name is the account's new name, under the same rules it was created with.\nRequired.",
		},
	})
}
