// Code generated by zipdoc; DO NOT EDIT.
//
// The dashboards face's slice of the package extraction, split into its own file
// so concurrent slices do not contend on zipdoc_gen.go; a later `go generate
// -run zipdoc ./` folds every slice back into zipdoc_gen.go, at which point
// this file is deleted.

package o11y

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/o11y/dashboard_views/:id", zip.Doc{
		Description: "Removes a saved view. Saved views are shared org-wide.\nDeleting a non-existent view refuses with the runtime's not-found.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id": "ID is the resource id from the path.",
		},
	})
	zip.Describe("DELETE /v1/o11y/dashboards/:id", zip.Doc{
		Description: "Deletes a v2-shape dashboard along with its tag relations.\nLocked dashboards are rejected.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id": "ID is the resource id from the path.",
		},
	})
	zip.Describe("DELETE /v1/o11y/dashboards/:id/lock", zip.Doc{
		Description: "Unlocks a v2-shape dashboard. Only the dashboard's creator or\nan org admin may lock or unlock.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id": "ID is the resource id from the path.",
		},
	})
	zip.Describe("DELETE /v1/o11y/dashboards/:id/public", zip.Doc{
		Description: "Deletes the public-sharing config and disables public\nsharing of a dashboard.\n\nCallers need the admin role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id": "ID is the resource id from the path.",
		},
	})
	zip.Describe("DELETE /v1/o11y/users/me/dashboards/:id/pins", zip.Doc{
		Description: "Removes the caller's pin for a dashboard. Idempotent —\nunpinning a dashboard that was not pinned still succeeds.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id": "ID is the resource id from the path.",
		},
	})
	zip.Describe("GET /v1/o11y/dashboard_views", zip.Doc{
		Description: "Returns every saved view in the calling user's org. Saved\nviews are shared org-wide.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardView.createdAt":     "CreatedAt is when the view was created.",
			"O11yDashboardView.data":          "Data is the listing state the view captures.",
			"O11yDashboardView.id":            "ID is the saved view's id.",
			"O11yDashboardView.name":          "Name is the saved view's name.",
			"O11yDashboardView.orgId":         "OrgID is the org the view belongs to.",
			"O11yDashboardView.updatedAt":     "UpdatedAt is when it last changed.",
			"O11yDashboardViewData.order":     "Order is the captured sort direction.",
			"O11yDashboardViewData.query":     "Query is the captured filter DSL.",
			"O11yDashboardViewData.sort":      "Sort is the captured sort field.",
			"O11yDashboardViewData.version":   "Version is the saved-view schema version; must be v1.",
			"O11yDashboardViewList.views":     "Views are the saved views, shared org-wide.",
			"O11yDashboardViewListOut.data":   "Data is the saved views.",
			"O11yDashboardViewListOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/dashboards", zip.Doc{
		Description: "Returns a page of v2-shape dashboards for the org. This is the\npure, user-independent list — it carries no pin state; use\ndashboardListForUserV2 for the personalized, pin-aware list. Supports a filter\nDSL (query), sort (updated_at/created_at/name), order (asc/desc), and\noffset-based pagination (limit/offset).\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardDisplay.description":    "Description says what the dashboard is for.",
			"O11yDashboardDisplay.name":           "Name is the human-facing dashboard name.",
			"O11yDashboardList.dashboards":        "Dashboards are the rows for this page.",
			"O11yDashboardList.tags":              "Tags are all tags in use across the org's dashboards.",
			"O11yDashboardList.total":             "Total is the count across all pages.",
			"O11yDashboardListItem.createdAt":     "CreatedAt is when the dashboard was created.",
			"O11yDashboardListItem.createdBy":     "CreatedBy is who created it.",
			"O11yDashboardListItem.id":            "ID is the dashboard's id.",
			"O11yDashboardListItem.image":         "Image is an optional cover image reference.",
			"O11yDashboardListItem.locked":        "Locked reports whether the dashboard is locked against edits.",
			"O11yDashboardListItem.name":          "Name is the dashboard's unique internal name.",
			"O11yDashboardListItem.orgId":         "OrgID is the org the dashboard belongs to.",
			"O11yDashboardListItem.schemaVersion": "SchemaVersion is the dashboard schema version.",
			"O11yDashboardListItem.source":        "Source is where the dashboard came from: user, system or integration.",
			"O11yDashboardListItem.spec":          "Spec is the display-only slice of the dashboard spec.",
			"O11yDashboardListItem.tags":          "Tags are the dashboard's tags.",
			"O11yDashboardListItem.updatedAt":     "UpdatedAt is when it last changed.",
			"O11yDashboardListItem.updatedBy":     "UpdatedBy is who last changed it.",
			"O11yDashboardListOut.data":           "Data is the list page.",
			"O11yDashboardListOut.status":         "Status is \"success\".",
			"O11yDashboardListParams.limit":       "Limit caps how many dashboards come back. Zero means the default of 20;\nthe runtime caps it at 200.",
			"O11yDashboardListParams.offset":      "Offset is how many dashboards to skip for pagination.",
			"O11yDashboardListParams.order":       "Order is the sort direction: asc or desc. Empty orders desc.",
			"O11yDashboardListParams.query":       "Query is the filter DSL over dashboard columns and tags, e.g.\n`name:cpu source:user`. Empty lists everything.",
			"O11yDashboardListParams.sort":        "Sort is the sort field: updated_at, created_at or name. Empty sorts by\nupdated_at.",
			"O11yDashboardListSpec.display":       "Display is the dashboard's display metadata.",
			"O11yDashboardTag.key":                "Key is the tag key.",
			"O11yDashboardTag.value":              "Value is the tag value.",
		},
	})
	zip.Describe("GET /v1/o11y/dashboards/:id", zip.Doc{
		Description: "Returns a v2-shape dashboard.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboard.createdAt":     "CreatedAt is when the dashboard was created.",
			"O11yDashboard.createdBy":     "CreatedBy is who created it.",
			"O11yDashboard.id":            "ID is the dashboard's id.",
			"O11yDashboard.image":         "Image is an optional cover image reference.",
			"O11yDashboard.locked":        "Locked reports whether the dashboard is locked against edits.",
			"O11yDashboard.name":          "Name is the dashboard's unique internal name.",
			"O11yDashboard.orgId":         "OrgID is the org the dashboard belongs to.",
			"O11yDashboard.schemaVersion": "SchemaVersion is the dashboard schema version.",
			"O11yDashboard.source":        "Source is where the dashboard came from: user, system or integration.",
			"O11yDashboard.spec":          "Spec is the Perses dashboard spec, carried verbatim as open JSON.",
			"O11yDashboard.tags":          "Tags are the dashboard's tags.",
			"O11yDashboard.updatedAt":     "UpdatedAt is when it last changed.",
			"O11yDashboard.updatedBy":     "UpdatedBy is who last changed it.",
			"O11yDashboardIDIn.id":        "ID is the resource id from the path.",
			"O11yDashboardOut.data":       "Data is the dashboard.",
			"O11yDashboardOut.status":     "Status is \"success\".",
			"O11yDashboardTag.key":        "Key is the tag key.",
			"O11yDashboardTag.value":      "Value is the tag value.",
		},
	})
	zip.Describe("GET /v1/o11y/dashboards/:id/public", zip.Doc{
		Description: "Returns the public-sharing config for a dashboard.\n\nCallers need the admin role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id":                 "ID is the resource id from the path.",
			"O11yPublicDashboard.defaultTimeRange": "DefaultTimeRange is the fixed window when the range is not caller-chosen.",
			"O11yPublicDashboard.publicPath":       "PublicPath is the public URL path the share is reachable at.",
			"O11yPublicDashboard.timeRangeEnabled": "TimeRangeEnabled reports whether the public page may pick its own range.",
			"O11yPublicDashboardOut.data":          "Data is the public-sharing config.",
			"O11yPublicDashboardOut.status":        "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/public/dashboards/:id", zip.Doc{
		Description: "Returns the sanitized dashboard data for public access —\nthe read a shared dashboard's public page makes.\n\nAnonymous, scoped to the public dashboard's read scope; the runtime's own gate\nenforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id":                    "ID is the resource id from the path.",
			"O11yPublicDashboard.defaultTimeRange":    "DefaultTimeRange is the fixed window when the range is not caller-chosen.",
			"O11yPublicDashboard.publicPath":          "PublicPath is the public URL path the share is reachable at.",
			"O11yPublicDashboard.timeRangeEnabled":    "TimeRangeEnabled reports whether the public page may pick its own range.",
			"O11yPublicDashboardData.dashboard":       "Dashboard is the sanitized dashboard.",
			"O11yPublicDashboardData.publicDashboard": "PublicDashboard is the public-sharing config.",
			"O11yPublicDashboardDataOut.data":         "Data is the sanitized dashboard and its share config.",
			"O11yPublicDashboardDataOut.status":       "Status is \"success\".",
			"O11yPublicDashboardV1.createdAt":         "CreatedAt is when the dashboard was created.",
			"O11yPublicDashboardV1.createdBy":         "CreatedBy is who created it.",
			"O11yPublicDashboardV1.data":              "Data is the sanitized widget data as stored, carried verbatim as open JSON.",
			"O11yPublicDashboardV1.id":                "ID is the dashboard's id.",
			"O11yPublicDashboardV1.locked":            "Locked reports whether the dashboard is locked.",
			"O11yPublicDashboardV1.org_id":            "OrgID is the org the dashboard belongs to.",
			"O11yPublicDashboardV1.source":            "Source is where the dashboard came from.",
			"O11yPublicDashboardV1.updatedAt":         "UpdatedAt is when it last changed.",
			"O11yPublicDashboardV1.updatedBy":         "UpdatedBy is who last changed it.",
		},
	})
	zip.Describe("GET /v1/o11y/public/dashboards/:id/widgets/:idx/query_range", zip.Doc{
		Description: "Returns the query-range result for one widget\nof a public dashboard. When the share fixes its own time range the caller's\nstartTime/endTime are ignored; otherwise they bound the window as millisecond\nepochs.\n\nAnonymous, scoped to the public dashboard's read scope; the runtime's own gate\nenforces it.",
		Fields: map[string]string{
			"O11yWidgetQueryRange.data":        "Data is the query result payload, carried verbatim as open JSON.",
			"O11yWidgetQueryRange.meta":        "Meta is the execution stats, carried verbatim as open JSON.",
			"O11yWidgetQueryRange.type":        "Type is the request type the result answers, e.g. time_series, scalar.",
			"O11yWidgetQueryRange.warning":     "Warning is any query warning, carried verbatim as open JSON when present.",
			"O11yWidgetQueryRangeIn.endTime":   "EndTime is the window end as a millisecond epoch. Used only when the share\nenables a caller-chosen time range.",
			"O11yWidgetQueryRangeIn.id":        "ID is the public dashboard id from the path.",
			"O11yWidgetQueryRangeIn.idx":       "Idx is the widget's index from the path.",
			"O11yWidgetQueryRangeIn.startTime": "StartTime is the window start as a millisecond epoch. Used only when the\nshare enables a caller-chosen time range.",
			"O11yWidgetQueryRangeOut.data":     "Data is the query-range result.",
			"O11yWidgetQueryRangeOut.status":   "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/users/me/dashboards", zip.Doc{
		Description: "Is dashboardListV2 personalized for the calling user:\neach dashboard carries the caller's pinned state, and pinned dashboards float to\nthe top of the requested ordering. Supports the same filter DSL, sort, order and\npagination.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardDisplay.description":    "Description says what the dashboard is for.",
			"O11yDashboardDisplay.name":           "Name is the human-facing dashboard name.",
			"O11yDashboardListForUser.dashboards": "Dashboards are the rows for this page, each with the caller's pin state.",
			"O11yDashboardListForUser.tags":       "Tags are all tags in use across the org's dashboards.",
			"O11yDashboardListForUser.total":      "Total is the count across all pages.",
			"O11yDashboardListForUserOut.data":    "Data is the list page with pins.",
			"O11yDashboardListForUserOut.status":  "Status is \"success\".",
			"O11yDashboardListItem.createdAt":     "CreatedAt is when the dashboard was created.",
			"O11yDashboardListItem.createdBy":     "CreatedBy is who created it.",
			"O11yDashboardListItem.id":            "ID is the dashboard's id.",
			"O11yDashboardListItem.image":         "Image is an optional cover image reference.",
			"O11yDashboardListItem.locked":        "Locked reports whether the dashboard is locked against edits.",
			"O11yDashboardListItem.name":          "Name is the dashboard's unique internal name.",
			"O11yDashboardListItem.orgId":         "OrgID is the org the dashboard belongs to.",
			"O11yDashboardListItem.schemaVersion": "SchemaVersion is the dashboard schema version.",
			"O11yDashboardListItem.source":        "Source is where the dashboard came from: user, system or integration.",
			"O11yDashboardListItem.spec":          "Spec is the display-only slice of the dashboard spec.",
			"O11yDashboardListItem.tags":          "Tags are the dashboard's tags.",
			"O11yDashboardListItem.updatedAt":     "UpdatedAt is when it last changed.",
			"O11yDashboardListItem.updatedBy":     "UpdatedBy is who last changed it.",
			"O11yDashboardListItemForUser.pinned": "Pinned reports whether the calling user has pinned this dashboard.",
			"O11yDashboardListParams.limit":       "Limit caps how many dashboards come back. Zero means the default of 20;\nthe runtime caps it at 200.",
			"O11yDashboardListParams.offset":      "Offset is how many dashboards to skip for pagination.",
			"O11yDashboardListParams.order":       "Order is the sort direction: asc or desc. Empty orders desc.",
			"O11yDashboardListParams.query":       "Query is the filter DSL over dashboard columns and tags, e.g.\n`name:cpu source:user`. Empty lists everything.",
			"O11yDashboardListParams.sort":        "Sort is the sort field: updated_at, created_at or name. Empty sorts by\nupdated_at.",
			"O11yDashboardListSpec.display":       "Display is the dashboard's display metadata.",
			"O11yDashboardTag.key":                "Key is the tag key.",
			"O11yDashboardTag.value":              "Value is the tag value.",
		},
	})
	zip.Describe("PATCH /v1/o11y/dashboards/:id", zip.Doc{
		Description: "Applies an RFC 6902 JSON Patch to a v2-shape dashboard. The\npatch is applied against the postable view (metadata, spec, tags), so individual\npanels, queries, variables, layouts or tags can be updated without re-sending the\nrest. Apply is lenient — remove on a missing path is a no-op and add creates any\nmissing parent objects — and the result is still validated. Locked dashboards are\nrejected. The request body is the bare JSON Patch operations array.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboard.createdAt":     "CreatedAt is when the dashboard was created.",
			"O11yDashboard.createdBy":     "CreatedBy is who created it.",
			"O11yDashboard.id":            "ID is the dashboard's id.",
			"O11yDashboard.image":         "Image is an optional cover image reference.",
			"O11yDashboard.locked":        "Locked reports whether the dashboard is locked against edits.",
			"O11yDashboard.name":          "Name is the dashboard's unique internal name.",
			"O11yDashboard.orgId":         "OrgID is the org the dashboard belongs to.",
			"O11yDashboard.schemaVersion": "SchemaVersion is the dashboard schema version.",
			"O11yDashboard.source":        "Source is where the dashboard came from: user, system or integration.",
			"O11yDashboard.spec":          "Spec is the Perses dashboard spec, carried verbatim as open JSON.",
			"O11yDashboard.tags":          "Tags are the dashboard's tags.",
			"O11yDashboard.updatedAt":     "UpdatedAt is when it last changed.",
			"O11yDashboard.updatedBy":     "UpdatedBy is who last changed it.",
			"O11yDashboardOut.data":       "Data is the dashboard.",
			"O11yDashboardOut.status":     "Status is \"success\".",
			"O11yDashboardPatchIn.id":     "ID is the dashboard id from the path.",
			"O11yDashboardPatchIn.ops":    "Ops are the JSON Patch operations, applied in order. On the wire this IS the\nrequest body — a bare array, not an object.",
			"O11yDashboardPatchOp.from":   "From is the source JSON Pointer for move and copy; ignored otherwise.",
			"O11yDashboardPatchOp.op":     "Op is the verb: add, remove, replace, move, copy or test.",
			"O11yDashboardPatchOp.path":   "Path is a JSON Pointer into the postable dashboard, e.g.\n/spec/display/name, /spec/panels/<id>, /tags/-.",
			"O11yDashboardPatchOp.value":  "Value is the value to add/replace/test; its type depends on Path. Required\nfor add, replace and test; ignored otherwise.",
			"O11yDashboardTag.key":        "Key is the tag key.",
			"O11yDashboardTag.value":      "Value is the tag value.",
		},
	})
	zip.Describe("POST /v1/o11y/dashboard_views", zip.Doc{
		Description: "Persists the calling user's dashboard-listing state (query,\nsort, order) as a named, reusable view shared across the org.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardView.createdAt":    "CreatedAt is when the view was created.",
			"O11yDashboardView.data":         "Data is the listing state the view captures.",
			"O11yDashboardView.id":           "ID is the saved view's id.",
			"O11yDashboardView.name":         "Name is the saved view's name.",
			"O11yDashboardView.orgId":        "OrgID is the org the view belongs to.",
			"O11yDashboardView.updatedAt":    "UpdatedAt is when it last changed.",
			"O11yDashboardViewData.order":    "Order is the captured sort direction.",
			"O11yDashboardViewData.query":    "Query is the captured filter DSL.",
			"O11yDashboardViewData.sort":     "Sort is the captured sort field.",
			"O11yDashboardViewData.version":  "Version is the saved-view schema version; must be v1.",
			"O11yDashboardViewOut.data":      "Data is the saved view.",
			"O11yDashboardViewOut.status":    "Status is \"success\".",
			"O11yDashboardViewPostable.data": "Data is the listing state the view captures.",
			"O11yDashboardViewPostable.name": "Name is the saved view's name; at most 32 characters, no surrounding space.",
		},
	})
	zip.Describe("POST /v1/o11y/dashboards", zip.Doc{
		Description: "Creates a dashboard in the v2 format that follows the Perses\nspec and answers with the stored dashboard.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboard.createdAt":             "CreatedAt is when the dashboard was created.",
			"O11yDashboard.createdBy":             "CreatedBy is who created it.",
			"O11yDashboard.id":                    "ID is the dashboard's id.",
			"O11yDashboard.image":                 "Image is an optional cover image reference.",
			"O11yDashboard.locked":                "Locked reports whether the dashboard is locked against edits.",
			"O11yDashboard.name":                  "Name is the dashboard's unique internal name.",
			"O11yDashboard.orgId":                 "OrgID is the org the dashboard belongs to.",
			"O11yDashboard.schemaVersion":         "SchemaVersion is the dashboard schema version.",
			"O11yDashboard.source":                "Source is where the dashboard came from: user, system or integration.",
			"O11yDashboard.spec":                  "Spec is the Perses dashboard spec, carried verbatim as open JSON.",
			"O11yDashboard.tags":                  "Tags are the dashboard's tags.",
			"O11yDashboard.updatedAt":             "UpdatedAt is when it last changed.",
			"O11yDashboard.updatedBy":             "UpdatedBy is who last changed it.",
			"O11yDashboardOut.data":               "Data is the dashboard.",
			"O11yDashboardOut.status":             "Status is \"success\".",
			"O11yDashboardPostable.generateName":  "GenerateName derives a fresh unique name from spec.display.name instead of\ntaking Name.",
			"O11yDashboardPostable.image":         "Image is an optional cover image reference.",
			"O11yDashboardPostable.name":          "Name is the dashboard's unique internal name (a DNS-1123 label). Omit it\nwith generateName to derive one from the display name.",
			"O11yDashboardPostable.schemaVersion": "SchemaVersion is the dashboard schema version; must be the current v6.",
			"O11yDashboardPostable.spec":          "Spec is the Perses dashboard spec (display, variables, panels, layouts,\ndatasources). Its plugin-defined leaves are open JSON, carried verbatim.",
			"O11yDashboardPostable.tags":          "Tags are the dashboard's tags; at most ten, and none may use a reserved DSL\nkey.",
			"O11yDashboardPostableTag.key":        "Key is the tag key.",
			"O11yDashboardPostableTag.value":      "Value is the tag value.",
			"O11yDashboardTag.key":                "Key is the tag key.",
			"O11yDashboardTag.value":              "Value is the tag value.",
		},
	})
	zip.Describe("POST /v1/o11y/dashboards/:id/clone", zip.Doc{
		Description: "Clones an existing v2-shape dashboard. User and integration\ndashboards can be cloned; system dashboards are rejected. The clone keeps the\nsource's display name, panels and tags, but gets a freshly generated unique\ninternal name and is always created as an unlocked user dashboard owned by the\ncaller.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboard.createdAt":     "CreatedAt is when the dashboard was created.",
			"O11yDashboard.createdBy":     "CreatedBy is who created it.",
			"O11yDashboard.id":            "ID is the dashboard's id.",
			"O11yDashboard.image":         "Image is an optional cover image reference.",
			"O11yDashboard.locked":        "Locked reports whether the dashboard is locked against edits.",
			"O11yDashboard.name":          "Name is the dashboard's unique internal name.",
			"O11yDashboard.orgId":         "OrgID is the org the dashboard belongs to.",
			"O11yDashboard.schemaVersion": "SchemaVersion is the dashboard schema version.",
			"O11yDashboard.source":        "Source is where the dashboard came from: user, system or integration.",
			"O11yDashboard.spec":          "Spec is the Perses dashboard spec, carried verbatim as open JSON.",
			"O11yDashboard.tags":          "Tags are the dashboard's tags.",
			"O11yDashboard.updatedAt":     "UpdatedAt is when it last changed.",
			"O11yDashboard.updatedBy":     "UpdatedBy is who last changed it.",
			"O11yDashboardIDIn.id":        "ID is the resource id from the path.",
			"O11yDashboardOut.data":       "Data is the dashboard.",
			"O11yDashboardOut.status":     "Status is \"success\".",
			"O11yDashboardTag.key":        "Key is the tag key.",
			"O11yDashboardTag.value":      "Value is the tag value.",
		},
	})
	zip.Describe("POST /v1/o11y/dashboards/:id/public", zip.Doc{
		Description: "Creates the public-sharing config for a dashboard and\nenables public sharing, answering with the new share's id.\n\nCallers need the admin role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yIdentifiable.id":                       "ID is the created resource's id.",
			"O11yIdentifiableOut.data":                  "Data is the created resource's id.",
			"O11yIdentifiableOut.status":                "Status is \"success\".",
			"O11yPublicDashboardWrite.defaultTimeRange": "DefaultTimeRange is the fixed window as a Go duration, e.g. 1h, 30m.",
			"O11yPublicDashboardWrite.timeRangeEnabled": "TimeRangeEnabled lets the public page pick its own time range; when false\nthe share fixes DefaultTimeRange.",
			"O11yPublicDashboardWriteIn.id":             "ID is the dashboard id from the path.",
		},
	})
	zip.Describe("PUT /v1/o11y/dashboard_views/:id", zip.Doc{
		Description: "Replaces a saved view's name and data. Saved views are shared\norg-wide.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardView.createdAt":    "CreatedAt is when the view was created.",
			"O11yDashboardView.data":         "Data is the listing state the view captures.",
			"O11yDashboardView.id":           "ID is the saved view's id.",
			"O11yDashboardView.name":         "Name is the saved view's name.",
			"O11yDashboardView.orgId":        "OrgID is the org the view belongs to.",
			"O11yDashboardView.updatedAt":    "UpdatedAt is when it last changed.",
			"O11yDashboardViewData.order":    "Order is the captured sort direction.",
			"O11yDashboardViewData.query":    "Query is the captured filter DSL.",
			"O11yDashboardViewData.sort":     "Sort is the captured sort field.",
			"O11yDashboardViewData.version":  "Version is the saved-view schema version; must be v1.",
			"O11yDashboardViewOut.data":      "Data is the saved view.",
			"O11yDashboardViewOut.status":    "Status is \"success\".",
			"O11yDashboardViewPostable.data": "Data is the listing state the view captures.",
			"O11yDashboardViewPostable.name": "Name is the saved view's name; at most 32 characters, no surrounding space.",
			"O11yDashboardViewUpdateIn.id":   "ID is the saved view id from the path.",
		},
	})
	zip.Describe("PUT /v1/o11y/dashboards/:id", zip.Doc{
		Description: "Updates a v2-shape dashboard's metadata, spec and tag set.\nThe name is immutable and locked dashboards are rejected.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboard.createdAt":              "CreatedAt is when the dashboard was created.",
			"O11yDashboard.createdBy":              "CreatedBy is who created it.",
			"O11yDashboard.id":                     "ID is the dashboard's id.",
			"O11yDashboard.image":                  "Image is an optional cover image reference.",
			"O11yDashboard.locked":                 "Locked reports whether the dashboard is locked against edits.",
			"O11yDashboard.name":                   "Name is the dashboard's unique internal name.",
			"O11yDashboard.orgId":                  "OrgID is the org the dashboard belongs to.",
			"O11yDashboard.schemaVersion":          "SchemaVersion is the dashboard schema version.",
			"O11yDashboard.source":                 "Source is where the dashboard came from: user, system or integration.",
			"O11yDashboard.spec":                   "Spec is the Perses dashboard spec, carried verbatim as open JSON.",
			"O11yDashboard.tags":                   "Tags are the dashboard's tags.",
			"O11yDashboard.updatedAt":              "UpdatedAt is when it last changed.",
			"O11yDashboard.updatedBy":              "UpdatedBy is who last changed it.",
			"O11yDashboardOut.data":                "Data is the dashboard.",
			"O11yDashboardOut.status":              "Status is \"success\".",
			"O11yDashboardPostableTag.key":         "Key is the tag key.",
			"O11yDashboardPostableTag.value":       "Value is the tag value.",
			"O11yDashboardTag.key":                 "Key is the tag key.",
			"O11yDashboardTag.value":               "Value is the tag value.",
			"O11yDashboardUpdatable.image":         "Image is an optional cover image reference.",
			"O11yDashboardUpdatable.name":          "Name must equal the dashboard's existing name — it is immutable.",
			"O11yDashboardUpdatable.schemaVersion": "SchemaVersion is the dashboard schema version; must be the current v6.",
			"O11yDashboardUpdatable.spec":          "Spec is the replacement Perses spec, carried verbatim as open JSON.",
			"O11yDashboardUpdatable.tags":          "Tags replace the dashboard's tags; at most ten.",
			"O11yDashboardUpdateIn.id":             "ID is the dashboard id from the path.",
		},
	})
	zip.Describe("PUT /v1/o11y/dashboards/:id/lock", zip.Doc{
		Description: "Locks a v2-shape dashboard. Only the dashboard's creator or an\norg admin may lock or unlock.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id": "ID is the resource id from the path.",
		},
	})
	zip.Describe("PUT /v1/o11y/dashboards/:id/public", zip.Doc{
		Description: "Updates the public-sharing config for a dashboard.\n\nCallers need the admin role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yPublicDashboardWrite.defaultTimeRange": "DefaultTimeRange is the fixed window as a Go duration, e.g. 1h, 30m.",
			"O11yPublicDashboardWrite.timeRangeEnabled": "TimeRangeEnabled lets the public page pick its own time range; when false\nthe share fixes DefaultTimeRange.",
			"O11yPublicDashboardWriteIn.id":             "ID is the dashboard id from the path.",
		},
	})
	zip.Describe("PUT /v1/o11y/users/me/dashboards/:id/pins", zip.Doc{
		Description: "Pins a dashboard for the calling user. A user can pin at most ten\ndashboards; pinning at the limit refuses with the runtime's conflict. Re-pinning\nan already-pinned dashboard is a no-op success. Pinning mutates only the caller's\npin list, not the dashboard, so a viewer may pin what a viewer may read.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardIDIn.id": "ID is the resource id from the path.",
		},
	})
}
