// Code generated by zipdoc; DO NOT EDIT.
//
// The infra slice's entries, split out of zipdoc_gen.go so concurrent slices
// do not contend on one generated file; regenerating the package folds them
// back together, which is the intended end state.

package o11y

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/o11y/clusters/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys Kubernetes clusters\nreport, for building cluster filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/clusters/attribute_values", zip.Doc{
		Description: "Lists the values one cluster attribute key has taken,\nfor building cluster filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/daemonsets/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys Kubernetes daemonsets\nreport, for building daemonset filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/daemonsets/attribute_values", zip.Doc{
		Description: "Lists the values one daemonset attribute key has\ntaken, for building daemonset filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/deployments/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys Kubernetes\ndeployments report, for building deployment filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/deployments/attribute_values", zip.Doc{
		Description: "Lists the values one deployment attribute key has\ntaken, for building deployment filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/hosts/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys hosts report, for building\nhost filters — each with its data type and whether it is a materialized\ncolumn.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/hosts/attribute_values", zip.Doc{
		Description: "Lists the values one host attribute key has taken, for\nbuilding host filters — string, number and bool values in their own lists.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/infra_monitoring/checks", zip.Doc{
		Description: "Reports whether the metrics and attributes an infra-monitoring\nsection needs are being received — for each collector receiver or processor\ninvolved, what is present and what is missing, with a user-facing message\nand a docs link per missing piece. Ready is true only when nothing is\nmissing.",
		Fields: map[string]string{
			"O11yInfraChecksIn.type":    "Type is the section to check — hosts, processes, pods, nodes,\ndeployments, daemonsets, statefulsets, jobs, namespaces, clusters or\nvolumes. Required.",
			"O11yInfraChecksOut.data":   "Data holds what is present, what is missing and whether the section is\nready.",
			"O11yInfraChecksOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/jobs/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys Kubernetes jobs report, for\nbuilding job filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/jobs/attribute_values", zip.Doc{
		Description: "Lists the values one job attribute key has taken, for\nbuilding job filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/namespaces/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys Kubernetes namespaces\nreport, for building namespace filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/namespaces/attribute_values", zip.Doc{
		Description: "Lists the values one namespace attribute key has\ntaken, for building namespace filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/nodes/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys Kubernetes nodes report,\nfor building node filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/nodes/attribute_values", zip.Doc{
		Description: "Lists the values one node attribute key has taken, for\nbuilding node filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/pods/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys Kubernetes pods report, for\nbuilding pod filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/pods/attribute_values", zip.Doc{
		Description: "Lists the values one pod attribute key has taken, for\nbuilding pod filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/processes/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys processes report, for\nbuilding process filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/processes/attribute_values", zip.Doc{
		Description: "Lists the values one process attribute key has taken,\nfor building process filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/pvcs/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys persistent volume claims\nreport, for building volume filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/pvcs/attribute_values", zip.Doc{
		Description: "Lists the values one persistent-volume-claim attribute\nkey has taken, for building volume filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/statefulsets/attribute_keys", zip.Doc{
		Description: "Lists the metric attribute keys Kubernetes\nstatefulsets report, for building statefulset filters.",
		Fields: map[string]string{
			"O11yInfraAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yInfraAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yInfraAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yInfraAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yInfraAttributeKeysOut.data":              "Data holds the keys.",
			"O11yInfraAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/statefulsets/attribute_values", zip.Doc{
		Description: "Lists the values one statefulset attribute key\nhas taken, for building statefulset filters.",
		Fields: map[string]string{
			"O11yInfraAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yInfraAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under, e.g.\nnoop, count, avg. The runtime requires it for non-metrics sources.",
			"O11yInfraAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yInfraAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — metrics for the infra\nfaces. The runtime requires it.",
			"O11yInfraAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64,\nfloat64 or bool. Empty means unspecified.",
			"O11yInfraAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yInfraAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yInfraAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yInfraAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yInfraAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/clusters/list", zip.Doc{
		Description: "Lists Kubernetes clusters over a time range, each with its CPU\nand memory usage against allocatable capacity and its attributes;\nfilterable, groupable and paginated.",
		Fields: map[string]string{
			"ClusterListRequest.end":    "epoch time in ms",
			"ClusterListRequest.start":  "epoch time in ms",
			"O11yClusterListOut.data":   "Data holds the cluster records.",
			"O11yClusterListOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/daemonsets/list", zip.Doc{
		Description: "Lists Kubernetes daemonsets over a time range, each with the\nCPU and memory its pods used against request and limit, desired and\navailable node counts, restarts and attributes; filterable, groupable and\npaginated.",
		Fields: map[string]string{
			"DaemonSetListRequest.end":    "epoch time in ms",
			"DaemonSetListRequest.start":  "epoch time in ms",
			"O11yDaemonSetListOut.data":   "Data holds the daemonset records.",
			"O11yDaemonSetListOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/deployments/list", zip.Doc{
		Description: "Lists Kubernetes deployments over a time range, each with the\nCPU and memory its pods used against request and limit, desired and\navailable replica counts, restarts and attributes; filterable, groupable and\npaginated.",
		Fields: map[string]string{
			"DeploymentListRequest.end":    "epoch time in ms",
			"DeploymentListRequest.start":  "epoch time in ms",
			"O11yDeploymentListOut.data":   "Data holds the deployment records.",
			"O11yDeploymentListOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/hosts/list", zip.Doc{
		Description: "Lists monitored hosts over a time range, each with its CPU,\nmemory, I/O wait and 15-minute load, whether it is actively reporting, its\nOS and its attributes; filterable, groupable and paginated. The answer also\nsays whether any host metrics were received at all and which clusters and\nnodes sent them, so an empty page is distinguishable from a fleet that never\nreported.",
		Fields: map[string]string{
			"HostListRequest.end":    "epoch time in ms",
			"HostListRequest.start":  "epoch time in ms",
			"O11yHostListOut.data":   "Data holds the host records and the fleet's reporting state.",
			"O11yHostListOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/clusters", zip.Doc{
		Description: "Lists Kubernetes clusters with CPU and memory usage against\nallocatable capacity summed over their nodes, plus per-group node readiness\nand pod phase counts. Rows answer as 'list' under the default\nk8s.cluster.name grouping or 'grouped_list' under a custom groupBy; a metric\nwith no data in the window answers -1. Filterable by expression, orderable\nby usage or allocatable, paginated by offset and limit.",
		Fields: map[string]string{
			"ClusterRecord.clusterName":       "TODO(nikhilmantri0902): once the underlying attr key is migrated to\nk8s.cluster.uid (see ClusterNameAttrKey), surface ClusterUID alongside\n(or replace) ClusterName.",
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraClustersOut.data":       "Data holds the rows.",
			"O11yInfraClustersOut.status":     "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/daemonsets", zip.Doc{
		Description: "Lists Kubernetes daemonsets with the CPU and memory their\npods used against request and limit, the latest desired and current\nscheduled NODE counts (node counts, not pod counts), and per-group pod phase\ncounts. Rows answer as 'list' under the default k8s.daemonset.name grouping\nor 'grouped_list' under a custom groupBy; a metric with no data in the\nwindow answers -1. Filterable by expression, orderable by the pod metrics or\nthe node counts, paginated by offset and limit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraDaemonSetsOut.data":     "Data holds the rows.",
			"O11yInfraDaemonSetsOut.status":   "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/deployments", zip.Doc{
		Description: "Lists Kubernetes deployments with the CPU and memory their\npods used against request and limit, the latest desired and available\nreplica counts, and per-group pod phase counts. Rows answer as 'list' under\nthe default k8s.deployment.name grouping or 'grouped_list' under a custom\ngroupBy; a metric with no data in the window answers -1. Filterable by\nexpression, orderable by the pod metrics or the replica counts, paginated by\noffset and limit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraDeploymentsOut.data":    "Data holds the rows.",
			"O11yInfraDeploymentsOut.status":  "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/hosts", zip.Doc{
		Description: "Lists hosts with key infrastructure metrics — CPU, memory, I/O\nwait and disk usage percentages and 15-minute load — plus an\nactive/inactive status from whether the host reported in the last ten\nminutes. Rows answer as 'list' under the default host.name grouping or\n'grouped_list' under a custom groupBy; a metric with no data in the window\nanswers -1. Filterable by expression and by status, orderable by any of the\nfive metrics, paginated by offset and limit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraHostsOut.data":          "Data holds the rows.",
			"O11yInfraHostsOut.status":        "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/jobs", zip.Doc{
		Description: "Lists Kubernetes jobs with the CPU and memory their pods used\nagainst request and limit, the latest desired-successful, active, failed and\nsuccessful pod counters, and per-group pod phase counts — the phase counts\nare current state while the counters are cumulative over the job's life.\nRows answer as 'list' under the default k8s.job.name grouping or\n'grouped_list' under a custom groupBy; a metric with no data in the window\nanswers -1. Filterable by expression, orderable by the pod metrics or the\njob counters, paginated by offset and limit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraJobsOut.data":           "Data holds the rows.",
			"O11yInfraJobsOut.status":         "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/namespaces", zip.Doc{
		Description: "Lists Kubernetes namespaces with the CPU and memory their\npods used and per-group pod phase counts. Rows answer as 'list' under the\ndefault k8s.namespace.name grouping or 'grouped_list' under a custom\ngroupBy, aggregating pods either way; a metric with no data in the window\nanswers -1. Filterable by expression, orderable by cpu or memory, paginated\nby offset and limit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraNamespacesOut.data":     "Data holds the rows.",
			"O11yInfraNamespacesOut.status":   "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/nodes", zip.Doc{
		Description: "Lists Kubernetes nodes with CPU and memory usage against\nallocatable capacity, per-group readiness counts and per-group phase counts\nfor the pods scheduled on them. Rows answer as 'list' under the default\nk8s.node.name grouping (each row one node with its readiness condition) or\n'grouped_list' under a custom groupBy; a metric with no data in the window\nanswers -1. Filterable by expression, orderable by usage or allocatable,\npaginated by offset and limit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraNodesOut.data":          "Data holds the rows.",
			"O11yInfraNodesOut.status":        "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/pods", zip.Doc{
		Description: "Lists Kubernetes pods with CPU and memory usage against request\nand limit, the pod's phase and its age, plus its namespace, node, owning\nworkload and cluster attributes. Rows answer as 'list' under the default\nk8s.pod.uid grouping (each row one pod) or 'grouped_list' under a custom\ngroupBy (each row aggregating its pods with per-phase counts); a metric with\nno data in the window answers -1. Filterable by expression, orderable by the\nsix pod metrics, paginated by offset and limit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraPodsOut.data":           "Data holds the rows.",
			"O11yInfraPodsOut.status":         "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/pvcs", zip.Doc{
		Description: "Lists Kubernetes persistent volume claims with available,\ncapacity and used bytes and inode counts, plus the claim's pod, namespace,\nnode, statefulset and cluster attributes. Rows answer as 'list' under the\ndefault k8s.persistentvolumeclaim.name grouping or 'grouped_list' under a\ncustom groupBy; a metric with no data in the window answers -1. Filterable\nby expression, orderable by the six volume metrics, paginated by offset and\nlimit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraVolumesOut.data":        "Data holds the rows.",
			"O11yInfraVolumesOut.status":      "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/infra_monitoring/statefulsets", zip.Doc{
		Description: "Lists Kubernetes statefulsets with the CPU and memory\ntheir pods used against request and limit, the latest desired and current\nreplica counts, and per-group pod phase counts. Rows answer as 'list' under\nthe default k8s.statefulset.name grouping or 'grouped_list' under a custom\ngroupBy; a metric with no data in the window answers -1. Filterable by\nexpression, orderable by the pod metrics or the replica counts, paginated by\noffset and limit.",
		Fields: map[string]string{
			"Filter.expression":               "expression to filter by following the filter syntax",
			"O11yInfraStatefulSetsOut.data":   "Data holds the rows.",
			"O11yInfraStatefulSetsOut.status": "Status is \"success\".",
			"OrderBy.direction":               "direction to order by",
			"OrderBy.key":                     "key to order by",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("POST /v1/o11y/jobs/list", zip.Doc{
		Description: "Lists Kubernetes jobs over a time range, each with the CPU and\nmemory its pods used against request and limit, desired-successful, active,\nfailed and successful pod counts, restarts and attributes; filterable,\ngroupable and paginated.",
		Fields: map[string]string{
			"JobListRequest.end":    "epoch time in ms",
			"JobListRequest.start":  "epoch time in ms",
			"O11yJobListOut.data":   "Data holds the job records.",
			"O11yJobListOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/namespaces/list", zip.Doc{
		Description: "Lists Kubernetes namespaces over a time range, each with the\nCPU and memory its pods used, their phase counts and its attributes;\nfilterable, groupable and paginated.",
		Fields: map[string]string{
			"NamespaceListRequest.end":    "epoch time in ms",
			"NamespaceListRequest.start":  "epoch time in ms",
			"O11yNamespaceListOut.data":   "Data holds the namespace records.",
			"O11yNamespaceListOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/nodes/list", zip.Doc{
		Description: "Lists Kubernetes nodes over a time range, each with its CPU and\nmemory usage against allocatable capacity, readiness condition counts and\nattributes; filterable, groupable and paginated.",
		Fields: map[string]string{
			"NodeListRequest.end":    "epoch time in ms",
			"NodeListRequest.start":  "epoch time in ms",
			"O11yNodeListOut.data":   "Data holds the node records.",
			"O11yNodeListOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/pods/list", zip.Doc{
		Description: "Lists Kubernetes pods over a time range, each with its CPU and\nmemory usage against request and limit, restart count, phase counts and\nattributes; filterable, groupable and paginated.",
		Fields: map[string]string{
			"O11yPodListOut.data":   "Data holds the pod records.",
			"O11yPodListOut.status": "Status is \"success\".",
			"PodListRequest.end":    "epoch time in ms",
			"PodListRequest.start":  "epoch time in ms",
		},
	})
	zip.Describe("POST /v1/o11y/processes/list", zip.Doc{
		Description: "Lists monitored processes over a time range, each with its name,\nPID, command line and CPU and memory usage; filterable, groupable and\npaginated.",
		Fields: map[string]string{
			"O11yProcessListOut.data":   "Data holds the process records.",
			"O11yProcessListOut.status": "Status is \"success\".",
			"ProcessListRequest.end":    "epoch time in ms",
			"ProcessListRequest.start":  "epoch time in ms",
		},
	})
	zip.Describe("POST /v1/o11y/pvcs/list", zip.Doc{
		Description: "Lists Kubernetes persistent volume claims over a time range, each\nwith its available, capacity and used bytes, inode counts and attributes;\nfilterable, groupable and paginated.",
		Fields: map[string]string{
			"O11yPvcListOut.data":     "Data holds the volume records.",
			"O11yPvcListOut.status":   "Status is \"success\".",
			"VolumeListRequest.end":   "epoch time in ms",
			"VolumeListRequest.start": "epoch time in ms",
		},
	})
	zip.Describe("POST /v1/o11y/statefulsets/list", zip.Doc{
		Description: "Lists Kubernetes statefulsets over a time range, each with\nthe CPU and memory its pods used against request and limit, desired and\navailable replica counts, restarts and attributes; filterable, groupable and\npaginated.",
		Fields: map[string]string{
			"O11yStatefulSetListOut.data":   "Data holds the statefulset records.",
			"O11yStatefulSetListOut.status": "Status is \"success\".",
			"StatefulSetListRequest.end":    "epoch time in ms",
			"StatefulSetListRequest.start":  "epoch time in ms",
		},
	})
}
