// Code generated by zipdoc; DO NOT EDIT.
//
// The integrations slice's entries, split out of zipdoc_gen.go so concurrent
// slices do not contend on one generated file; regenerating the package folds
// them back together, which is the intended end state.

package o11y

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/o11y/cloud_integrations/:cloud_provider/accounts/:id", zip.Doc{
		Description: "Tears down a connected account for the given provider, by\nid. Admin gate.",
	})
	zip.Describe("DELETE /v1/o11y/gateway/ingestion_keys/:keyId", zip.Doc{
		Description: "Removes an ingestion key, by id. Editor gate.",
	})
	zip.Describe("DELETE /v1/o11y/gateway/ingestion_keys/limits/:limitId", zip.Doc{
		Description: "Removes an ingestion key limit, by limit id. Editor\ngate.",
	})
	zip.Describe("GET /v1/o11y/cloud_integrations/:cloud_provider/accounts", zip.Doc{
		Description: "Lists the cloud-integration accounts connected for the given\nprovider. Admin gate.",
		Fields: map[string]string{
			"GCPAccountConfig.deploymentProjectId": "Project ID where central pub/sub for logs exist",
			"GCPAccountConfig.deploymentRegion":    "Project ID where otel collector will be deployed",
			"GCPAccountConfig.projectIds":          "List of project IDs to monitor",
			"O11yAccountsOut.data":                 "Data holds the connected accounts.",
			"O11yAccountsOut.status":               "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/cloud_integrations/:cloud_provider/accounts/:id", zip.Doc{
		Description: "Returns one connected account for the given provider, by id. Admin\ngate.",
		Fields: map[string]string{
			"GCPAccountConfig.deploymentProjectId": "Project ID where central pub/sub for logs exist",
			"GCPAccountConfig.deploymentRegion":    "Project ID where otel collector will be deployed",
			"GCPAccountConfig.projectIds":          "List of project IDs to monitor",
			"O11yAccountOut.data":                  "Data holds the account.",
			"O11yAccountOut.status":                "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/cloud_integrations/:cloud_provider/accounts/:id/services", zip.Doc{
		Description: "Lists the services metadata for one connected\naccount of the given provider, by account id. Admin gate.",
		Fields: map[string]string{
			"O11yServicesMetadataOut.data":   "Data holds the services metadata.",
			"O11yServicesMetadataOut.status": "Status is \"success\".",
			"ServiceMetadata.enabled":        "if the service is enabled for the account",
		},
	})
	zip.Describe("GET /v1/o11y/cloud_integrations/:cloud_provider/accounts/:id/services/:service_id", zip.Doc{
		Description: "Returns one service and its configuration for a connected\naccount of the given provider, by account id and service id. Admin gate.",
		Fields: map[string]string{
			"O11yServiceOut.data":   "Data holds the service.",
			"O11yServiceOut.status": "Status is \"success\".",
			"Service.overview":      "markdown",
		},
	})
	zip.Describe("GET /v1/o11y/cloud_integrations/:cloud_provider/credentials", zip.Doc{
		Description: "Returns the credentials the connecting agent needs\nto establish the cloud integration, for the given cloud provider. Admin gate.",
		Fields: map[string]string{
			"Credentials.o11yApiKey":    "PAT",
			"O11yCredentialsOut.data":   "Data holds the connection credentials.",
			"O11yCredentialsOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/cloud_integrations/:cloud_provider/services", zip.Doc{
		Description: "Lists the services the given provider can collect from,\noptionally scoped to one cloud integration. Admin gate.",
		Fields: map[string]string{
			"O11yListServicesMetadataIn.cloud_integration_id": "CloudIntegrationID, when set, scopes the listing to one cloud integration.",
			"O11yServicesMetadataOut.data":                    "Data holds the services metadata.",
			"O11yServicesMetadataOut.status":                  "Status is \"success\".",
			"ServiceMetadata.enabled":                         "if the service is enabled for the account",
		},
	})
	zip.Describe("GET /v1/o11y/cloud_integrations/:cloud_provider/services/:service_id", zip.Doc{
		Description: "Returns one service the given provider can collect from, by\nservice id, optionally scoped to one cloud integration. Admin gate.",
		Fields: map[string]string{
			"O11yGetServiceIn.cloud_integration_id": "CloudIntegrationID, when set, scopes the service to one cloud integration.",
			"O11yServiceOut.data":                   "Data holds the service.",
			"O11yServiceOut.status":                 "Status is \"success\".",
			"Service.overview":                      "markdown",
		},
	})
	zip.Describe("GET /v1/o11y/gateway/ingestion_keys", zip.Doc{
		Description: "Lists the workspace's ingestion keys, paginated. Editor\ngate.",
		Fields: map[string]string{
			"Limit.signal":                 "\"logs\", \"traces\", \"metrics\"",
			"O11yIngestionKeysIn.page":     "Page is the 1-based page number.",
			"O11yIngestionKeysIn.per_page": "PerPage is the page size.",
			"O11yIngestionKeysOut.data":    "Data holds the ingestion keys.",
			"O11yIngestionKeysOut.status":  "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/gateway/ingestion_keys/search", zip.Doc{
		Description: "Lists the workspace's ingestion keys whose name matches\nthe search, paginated. Editor gate.",
		Fields: map[string]string{
			"Limit.signal":                       "\"logs\", \"traces\", \"metrics\"",
			"O11yIngestionKeysOut.data":          "Data holds the ingestion keys.",
			"O11yIngestionKeysOut.status":        "Status is \"success\".",
			"O11ySearchIngestionKeysIn.name":     "Name is the substring to match ingestion-key names against.",
			"O11ySearchIngestionKeysIn.page":     "Page is the 1-based page number.",
			"O11ySearchIngestionKeysIn.per_page": "PerPage is the page size.",
		},
	})
	zip.Describe("GET /v1/o11y/integrations", zip.Doc{
		Description: "Lists the available integrations and whether each is\ninstalled in the caller's org, optionally narrowed to installed or\nnot-installed. Viewer gate.",
		Fields: map[string]string{
			"IntegrationSummary.description":      "A short description",
			"O11yIntegrationsListOut.data":        "Data holds the available integrations and their installed state.",
			"O11yIntegrationsListOut.status":      "Status is \"success\".",
			"O11yListIntegrationsIn.is_installed": "IsInstalled, when \"true\" or \"false\", keeps only integrations in that\ninstalled state; empty lists them all.",
		},
	})
	zip.Describe("GET /v1/o11y/integrations/:integrationId", zip.Doc{
		Description: "Returns one integration's full detail — its overview,\nconfiguration steps, collected data and assets — together with its\ninstallation record when the org has installed it. Viewer gate.",
		Fields: map[string]string{
			"AlertCompositeQuery.unit":               "Unit for the time series data shown in the graph\nThis is used to format the value and threshold",
			"IntegrationConnectionTests.metrics":     "Metric names expected to have been received for the integration.",
			"IntegrationDetails.overview":            "markdown",
			"IntegrationSummary.description":         "A short description",
			"NotificationSettings.newGroupEvalDelay": "NewGroupEvalDelay is the grace period for new series to be excluded from alerts evaluation",
			"O11yIntegrationOut.data":                "Data holds the integration and its installation record.",
			"O11yIntegrationOut.status":              "Status is \"success\".",
			"PipelineOperator.enable_flattening":     "json_parser fields",
			"PipelineOperator.layout":                "time_parser fields.",
			"PipelineOperator.mapping":               "Used in Severity Parsing and JSON Flattening mapping",
			"PipelineOperator.orderId":               "don't need the following in the final config",
			"PipelineOperator.overwrite_text":        "severity parser fields",
			"PipelineOperator.parse_to":              "optional keys depending on the type",
			"PostableRule.source":                    "Source captures the source url where rule has been created",
			"QueryEnvelope.spec":                     "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":                     "Type is the type of the query.",
		},
	})
	zip.Describe("GET /v1/o11y/integrations/:integrationId/connection_status", zip.Doc{
		Description: "Reports whether the integration's logs and\nmetrics have been received over the lookback window, so the console can show\na live connection state. An integration that is not installed answers with an\nempty status rather than an error. Viewer gate.",
		Fields: map[string]string{
			"O11yConnectionStatusIn.lookback_seconds":    "LookbackSeconds is how far back to look for received telemetry, in\nseconds.",
			"O11yConnectionStatusOut.data":               "Data holds the logs and metrics connection status.",
			"O11yConnectionStatusOut.status":             "Status is \"success\".",
			"SignalConnectionStatus.last_received_from":  "resource identifier",
			"SignalConnectionStatus.last_received_ts_ms": "epoch milliseconds",
		},
	})
	zip.Describe("GET /v1/o11y/zeus/hosts", zip.Doc{
		Description: "Returns the deployment's host info from Zeus. Viewer gate.",
		Fields: map[string]string{
			"O11yGettableHostOut.data":   "Data holds the host info.",
			"O11yGettableHostOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("PATCH /v1/o11y/gateway/ingestion_keys/:keyId", zip.Doc{
		Description: "Changes an ingestion key, by id. Editor gate.",
	})
	zip.Describe("PATCH /v1/o11y/gateway/ingestion_keys/limits/:limitId", zip.Doc{
		Description: "Changes an ingestion key limit, by limit id. Editor\ngate.",
	})
	zip.Describe("POST /v1/o11y/cloud-integrations/:cloud_provider/agent-check-in", zip.Doc{
		Description: "Is the deployed agent's check-in on its original\nhyphenated path, kept for backward compatibility with agents already\nrunning. Viewer gate — the agent's role is viewer.",
		Fields: map[string]string{
			"AWSCloudWatchLogsSubscription.filterPattern":       "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html\n\"\" implies no filtering is required",
			"AWSCloudWatchLogsSubscription.logGroupNamePrefix":  "subscribe to all logs groups with specified prefix.\neg: `/aws/rds/`",
			"AWSCloudWatchMetricStreamFilter.namespace":         "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-metricstream-metricstreamfilter.html",
			"AWSMetricsCollectionStrategy.streamFilters":        "to be used as https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-metricstream.html#cfn-cloudwatch-metricstream-includefilters",
			"AWSTelemetryCollectionStrategy.s3Buckets":          "Only available in S3 Sync Service Type in AWS",
			"AzureLogsCollectionStrategy.categoryGroups":        "List of categories to enable for diagnostic settings, to start with it will have 'allLogs' and no filtering.",
			"AzureTelemetryCollectionStrategy.resourceProvider": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types",
			"GettableAgentCheckIn.account_id":                   "Older fields for backward compatibility with existing AWS agents",
			"IntegrationConfig.enabled_regions":                 "backward compatible",
			"IntegrationConfig.telemetry":                       "backward compatible",
			"O11yAgentCheckInOut.data":                          "Data holds the check-in result.",
			"O11yAgentCheckInOut.status":                        "Status is \"success\".",
			"PostableAgentCheckIn.account_id":                   "following are backward compatible fields for older running agents, hence snake case JSON keys.\nWhich get mapped to new fields in AgentCheckInRequest",
			"PostableAgentCheckIn.cloud_account_id":             "=> ProviderAccountID",
		},
	})
	zip.Describe("POST /v1/o11y/cloud_integrations/:cloud_provider/accounts", zip.Doc{
		Description: "Connects a new cloud-integration account for the given\nprovider from its posted config and credentials, answering with the account\nand the artifact the agent deploys to complete the connection. Admin gate.",
		Fields: map[string]string{
			"ConnectionArtifact.aws":             "required till new providers are added",
			"Credentials.o11yApiKey":             "PAT",
			"O11yCreateAccountOut.data":          "Data holds the account and the connection artifact.",
			"O11yCreateAccountOut.status":        "Status is \"success\".",
			"PostableAccountConfig.AgentVersion": "as agent version is common for all providers, we can keep it at top level of this struct",
		},
	})
	zip.Describe("POST /v1/o11y/cloud_integrations/:cloud_provider/accounts/check_in", zip.Doc{
		Description: "Is the deployed agent's check-in — the path consistent with the\naccount surface, reporting the agent's account and telemetry state so the\nconnection can be tracked. Viewer gate — the agent's role is viewer.",
		Fields: map[string]string{
			"AWSCloudWatchLogsSubscription.filterPattern":       "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html\n\"\" implies no filtering is required",
			"AWSCloudWatchLogsSubscription.logGroupNamePrefix":  "subscribe to all logs groups with specified prefix.\neg: `/aws/rds/`",
			"AWSCloudWatchMetricStreamFilter.namespace":         "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-metricstream-metricstreamfilter.html",
			"AWSMetricsCollectionStrategy.streamFilters":        "to be used as https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-metricstream.html#cfn-cloudwatch-metricstream-includefilters",
			"AWSTelemetryCollectionStrategy.s3Buckets":          "Only available in S3 Sync Service Type in AWS",
			"AzureLogsCollectionStrategy.categoryGroups":        "List of categories to enable for diagnostic settings, to start with it will have 'allLogs' and no filtering.",
			"AzureTelemetryCollectionStrategy.resourceProvider": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types",
			"GettableAgentCheckIn.account_id":                   "Older fields for backward compatibility with existing AWS agents",
			"IntegrationConfig.enabled_regions":                 "backward compatible",
			"IntegrationConfig.telemetry":                       "backward compatible",
			"O11yAgentCheckInOut.data":                          "Data holds the check-in result.",
			"O11yAgentCheckInOut.status":                        "Status is \"success\".",
			"PostableAgentCheckIn.account_id":                   "following are backward compatible fields for older running agents, hence snake case JSON keys.\nWhich get mapped to new fields in AgentCheckInRequest",
			"PostableAgentCheckIn.cloud_account_id":             "=> ProviderAccountID",
		},
	})
	zip.Describe("POST /v1/o11y/gateway/ingestion_keys", zip.Doc{
		Description: "Mints an ingestion key for the workspace, answering with\nthe created key. Editor gate.",
		Fields: map[string]string{
			"O11yCreatedIngestionKeyOut.data":   "Data holds the created ingestion key.",
			"O11yCreatedIngestionKeyOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/gateway/ingestion_keys/:keyId/limits", zip.Doc{
		Description: "Sets a signal limit on an ingestion key, by key id,\nanswering with the created limit. Editor gate.",
		Fields: map[string]string{
			"O11yCreatedLimitOut.data":   "Data holds the created limit.",
			"O11yCreatedLimitOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/integrations/install", zip.Doc{
		Description: "Installs an integration into the caller's org from its id\nand configuration, answering with the installed catalog item. Viewer gate.",
		Fields: map[string]string{
			"IntegrationSummary.description": "A short description",
			"O11yInstallOut.data":            "Data holds the installed integration.",
			"O11yInstallOut.status":          "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/integrations/uninstall", zip.Doc{
		Description: "Removes an integration from the caller's org by id.\nViewer gate.",
		Fields: map[string]string{
			"O11yIntegrationAck.status": "Status is \"success\".",
		},
	})
	zip.Describe("PUT /v1/o11y/cloud_integrations/:cloud_provider/accounts/:id", zip.Doc{
		Description: "Changes a connected account's configuration for the given\nprovider, by id. Admin gate.",
		Fields: map[string]string{
			"UpdatableGCPAccountConfig.deploymentProjectId": "Project ID where central pub/sub for logs exist",
			"UpdatableGCPAccountConfig.deploymentRegion":    "Compute service region where otel collector will be deployed",
			"UpdatableGCPAccountConfig.projectIds":          "List of project IDs to monitor",
		},
	})
	zip.Describe("PUT /v1/o11y/cloud_integrations/:cloud_provider/accounts/:id/services/:service_id", zip.Doc{
		Description: "Changes a service's configuration for one connected account of\nthe given provider, by account id and service id. Admin gate.",
	})
	zip.Describe("PUT /v1/o11y/zeus/hosts", zip.Doc{
		Description: "Records the deployment's host in Zeus, overwriting any prior one.\nAdmin gate.",
	})
	zip.Describe("PUT /v1/o11y/zeus/profiles", zip.Doc{
		Description: "Records the deployment's profile in Zeus — how the team uses\nobservability today and what they plan — overwriting any prior one. Admin\ngate.",
	})
}
