// Code generated by zipdoc; DO NOT EDIT.

package o11y

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/o11y/disks", zip.Doc{
		Description: "Lists the storage disks the datastore reports, with their names and\ntypes.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDisk.name": "Name is the disk's name.",
			"O11yDisk.type": "Type is the disk's type, e.g. local or s3.",
		},
	})
	zip.Describe("GET /v1/o11y/features", zip.Doc{
		Description: "Returns the supported feature flags and their resolved values for\nthe caller's org.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yFeature.defaultVariant": "DefaultVariant is the variant used when nothing overrides it.",
			"O11yFeature.description":    "Description says what the flag gates.",
			"O11yFeature.kind":           "Kind is the flag's value kind, e.g. boolean.",
			"O11yFeature.name":           "Name is the flag's name.",
			"O11yFeature.resolvedValue":  "ResolvedValue is the value resolved for the caller's org.",
			"O11yFeature.stage":          "Stage is the flag's lifecycle stage, e.g. stable.",
			"O11yFeature.variants":       "Variants are the flag's possible values, by variant name.",
			"O11yFeaturesOut.data":       "Data are the features.",
			"O11yFeaturesOut.status":     "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/filter_suggestions", zip.Doc{
		Description: "Suggests attribute keys and example filter queries for the\nquery builder, seeded by what the org's own telemetry carries. Only the logs\ndata source is supported today.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yAttributeKey.dataType":               "DataType is the attribute's value type — string, int64, float64 or bool.",
			"O11yAttributeKey.isColumn":               "IsColumn marks an attribute materialized as its own column.",
			"O11yAttributeKey.isJSON":                 "IsJSON marks an attribute extracted from a JSON body.",
			"O11yAttributeKey.key":                    "Key is the attribute's name.",
			"O11yAttributeKey.type":                   "Type says where the attribute lives: tag or resource.",
			"O11yFilterItem.key":                      "Key is the attribute tested.",
			"O11yFilterItem.op":                       "Operator is the comparison, e.g. =, !=, in, contains.",
			"O11yFilterItem.value":                    "Value is what it is tested against; its type follows the attribute's.",
			"O11yFilterSet.items":                     "Items are the conditions.",
			"O11yFilterSet.op":                        "Operator combines the items — AND or OR.",
			"O11yFilterSuggestions.attributes":        "Attributes are the suggested attribute keys.",
			"O11yFilterSuggestions.example_queries":   "ExampleQueries are ready-to-run filter sets.",
			"O11yFilterSuggestionsIn.attributesLimit": "AttributesLimit caps how many attribute keys come back.",
			"O11yFilterSuggestionsIn.dataSource":      "DataSource is the signal suggestions are drawn from; only logs is\nsupported today. Required.",
			"O11yFilterSuggestionsIn.examplesLimit":   "ExamplesLimit caps how many example queries come back.",
			"O11yFilterSuggestionsIn.existingFilter":  "ExistingFilter is the current filter set, JSON base64url-encoded, so\nexample queries build on it rather than repeat it.",
			"O11yFilterSuggestionsIn.searchText":      "SearchText narrows attribute suggestions to keys containing it.",
			"O11yFilterSuggestionsOut.data":           "Data holds the suggestions.",
			"O11yFilterSuggestionsOut.status":         "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/global/config", zip.Doc{
		Description: "Returns the deployment's global configuration: its public\nendpoints and which identity providers are enabled. Open by design — the\nsign-in page reads it before anyone is signed in.\n\nOpen by design; the runtime's own gate is OpenAccess.",
		Fields: map[string]string{
			"O11yGlobalConfig.ai_assistant_url": "AIAssistantURL is the AI assistant endpoint, when one is exposed.",
			"O11yGlobalConfig.external_url":     "ExternalURL is the deployment's public URL.",
			"O11yGlobalConfig.identN":           "IdentN says which identity providers are enabled.",
			"O11yGlobalConfig.ingestion_url":    "IngestionURL is where telemetry is sent.",
			"O11yGlobalConfig.mcp_url":          "MCPURL is the MCP endpoint, when one is exposed.",
			"O11yGlobalConfigOut.data":          "Data is the configuration.",
			"O11yGlobalConfigOut.status":        "Status is \"success\".",
			"O11yIdentN.apikey":                 "APIKey is the API-key provider.",
			"O11yIdentN.impersonation":          "Impersonation is the impersonation provider.",
			"O11yIdentN.tokenizer":              "Tokenizer is the token-based provider.",
			"O11yToggle.enabled":                "Enabled says whether the feature is on.",
		},
	})
	zip.Describe("GET /v1/o11y/health", zip.Doc{
		Description: "Reports service health. With live set, the datastore connection is\nchecked too and an unhealthy store refuses with 503.\n\nOpen by design; the runtime's own gate is OpenAccess.",
		Fields: map[string]string{
			"O11yHealthIn.live":    "Live also checks the datastore connection; an unreachable store refuses\nwith 503.",
			"O11yHealthOut.status": "Status is \"ok\".",
		},
	})
	zip.Describe("GET /v1/o11y/infra_onboarding/k8s/status", zip.Doc{
		Description: "Reports how far Kubernetes infra onboarding has progressed:\nwhich metric families have arrived and, per pod, which required metadata\nlabels are present.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yK8sOnboarding.didSendClusterMetrics":       "DidSendClusterMetrics says whether cluster metrics have arrived.",
			"O11yK8sOnboarding.didSendNodeMetrics":          "DidSendNodeMetrics says whether node metrics have arrived.",
			"O11yK8sOnboarding.didSendPodMetrics":           "DidSendPodMetrics says whether pod metrics have arrived.",
			"O11yK8sOnboarding.isSendingOptionalPodMetrics": "IsSendingOptionalPodMetrics says whether optional pod metrics are\nflowing.",
			"O11yK8sOnboarding.isSendingRequiredMetadata":   "IsSendingRequiredMetadata reports, per pod, which required metadata\nlabels are present.",
			"O11yOnboardingOut.data":                        "Data is the progress report.",
			"O11yOnboardingOut.status":                      "Status is \"success\".",
			"O11yPodOnboarding.clusterName":                 "ClusterName is the pod's cluster.",
			"O11yPodOnboarding.hasClusterName":              "HasClusterName says whether the cluster label is present.",
			"O11yPodOnboarding.hasCronjobName":              "HasCronjobName says whether the cronjob label is present.",
			"O11yPodOnboarding.hasDaemonsetName":            "HasDaemonsetName says whether the daemonset label is present.",
			"O11yPodOnboarding.hasDeploymentName":           "HasDeploymentName says whether the deployment label is present.",
			"O11yPodOnboarding.hasJobName":                  "HasJobName says whether the job label is present.",
			"O11yPodOnboarding.hasNamespaceName":            "HasNamespaceName says whether the namespace label is present.",
			"O11yPodOnboarding.hasNodeName":                 "HasNodeName says whether the node label is present.",
			"O11yPodOnboarding.hasStatefulsetName":          "HasStatefulsetName says whether the statefulset label is present.",
			"O11yPodOnboarding.namespaceName":               "NamespaceName is the pod's namespace.",
			"O11yPodOnboarding.nodeName":                    "NodeName is the pod's node.",
			"O11yPodOnboarding.podName":                     "PodName is the pod.",
		},
	})
	zip.Describe("GET /v1/o11y/licenses", zip.Doc{
		Description: "Lists the org's licenses. This build has no enterprise edition, so\nthe list is intentionally empty.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yLicensesOut.data":   "Data are the licenses.",
			"O11yLicensesOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/licenses/active", zip.Doc{
		Description: "Activates the enterprise license. This build has no\nenterprise edition, so the licensing provider refuses it as unsupported.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yLicenseActiveOut.data":   "Data is the license.",
			"O11yLicenseActiveOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/metric/metric_metadata", zip.Doc{
		Description: "Returns one metric's metadata — its type, unit, description,\ntemporality, monotonicity and histogram buckets — optionally scoped to the\nmetric as one service reports it.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yMetricMetadataIn.metricName":   "MetricName is the metric to read.",
			"O11yMetricMetadataIn.serviceName":  "ServiceName scopes the metadata to the metric as one service reports it.",
			"O11yMetricMetadataOut.delta":       "Delta says whether the metric is delta-temporality.",
			"O11yMetricMetadataOut.description": "Description is the metric's description.",
			"O11yMetricMetadataOut.isMonotonic": "IsMonotonic says whether a sum only ever increases.",
			"O11yMetricMetadataOut.le":          "Le are the histogram bucket bounds, for histograms.",
			"O11yMetricMetadataOut.temporality": "Temporality is cumulative or delta.",
			"O11yMetricMetadataOut.type":        "Type is the metric's type — gauge, sum, histogram.",
			"O11yMetricMetadataOut.unit":        "Unit is the metric's unit.",
		},
	})
	zip.Describe("GET /v1/o11y/query", zip.Doc{
		Description: "Evaluates one instant PromQL query against the org's metrics and\nreturns the result at a single point in time.\n\nThe result is polymorphic by PromQL's own contract — a matrix, vector,\nscalar or string, discriminated by resultType — so it is carried verbatim\nrather than forced into one of its shapes.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yPromQueryIn.query":     "Query is the PromQL expression to evaluate. Required.",
			"O11yPromQueryIn.stats":     "Stats set to any non-empty value includes query statistics in the answer.",
			"O11yPromQueryIn.time":      "Time is the evaluation timestamp — epoch seconds or RFC3339. Empty\nevaluates at now.",
			"O11yPromQueryIn.timeout":   "Timeout caps evaluation time, as a duration in seconds.",
			"O11yPromQueryOut.data":     "Data is the evaluation result.",
			"O11yPromQueryOut.status":   "Status is \"success\".",
			"O11yPromResult.result":     "Result is the result in PromQL's own wire shape for ResultType, carried\nverbatim.",
			"O11yPromResult.resultType": "ResultType discriminates Result: matrix, vector, scalar or string.",
			"O11yPromResult.stats":      "Stats holds query statistics when the caller asked for them.",
		},
	})
	zip.Describe("GET /v1/o11y/settings/apdex", zip.Doc{
		Description: "Returns apdex settings for the named services.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yApdexIn.services":                 "Services are the service names, comma separated.",
			"O11yApdexOut.data":                    "Data holds one settings row per service.",
			"O11yApdexOut.status":                  "Status is \"success\".",
			"O11yApdexSettings.excludeStatusCodes": "ExcludeStatusCodes are status codes excluded from the score, comma\nseparated.",
			"O11yApdexSettings.id":                 "ID is the settings row's id.",
			"O11yApdexSettings.orgId":              "OrgID is the org the settings belong to.",
			"O11yApdexSettings.serviceName":        "ServiceName is the service.",
			"O11yApdexSettings.threshold":          "Threshold is the satisfied-response time in seconds.",
		},
	})
	zip.Describe("GET /v1/o11y/settings/ttl", zip.Doc{
		Description: "Returns the org's current retention policy: default TTL, custom\nper-label rules, and cold-storage settings where configured.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yRetentionMatch.key":                               "Key is the label to test.",
			"O11yRetentionMatch.values":                            "Values are the label values the rule matches.",
			"O11yRetentionOut.cold_storage_ttl_days":               "ColdStorageTTLDays is how old data must be before it moves, in days.",
			"O11yRetentionOut.cold_storage_volume":                 "ColdStorageVolume names the volume aged data moves to.",
			"O11yRetentionOut.default_ttl_days":                    "DefaultTTLDays is the retention for data no rule matches, in days.",
			"O11yRetentionOut.expected_logs_move_ttl_duration_hrs": "ExpectedLogsMoveTTLHours is the pending logs cold-storage move TTL, in\nhours.",
			"O11yRetentionOut.expected_logs_ttl_duration_hrs":      "ExpectedLogsTTLHours is the pending logs TTL, in hours.",
			"O11yRetentionOut.status":                              "Status is the last TTL operation's state.",
			"O11yRetentionOut.ttl_conditions":                      "TTLConditions are the ordered per-label rules; the first match wins.",
			"O11yRetentionOut.version":                             "Version is the policy format version.",
			"O11yRetentionRule.conditions":                         "Conditions all have to hold for the rule to match.",
			"O11yRetentionRule.ttlDays":                            "TTLDays is the retention applied when it does, in days.",
		},
	})
	zip.Describe("GET /v1/o11y/stats", zip.Doc{
		Description: "Returns the collected usage statistics for the caller's org, as the\nstats reporter aggregates them — a map whose keys are the reporter's own\ncounter names.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yOrgStatsOut.data":   "Data are the statistics, keyed by the reporter's own counter names.",
			"O11yOrgStatsOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/usage", zip.Doc{
		Description: "Returns ingestion usage counts bucketed over the requested window,\noptionally narrowed to one service.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yUsageIn.end":         "End is the window end, as epoch nanoseconds. Required.",
			"O11yUsageIn.service":     "Service narrows usage to one service. Empty covers all.",
			"O11yUsageIn.start":       "Start is the window start, as epoch nanoseconds. Required.",
			"O11yUsageIn.step":        "Step is the bucket width in seconds. The runtime requires it.",
			"O11yUsageItem.count":     "Count is how many spans were ingested in the bucket.",
			"O11yUsageItem.time":      "Time is the bucket start.",
			"O11yUsageItem.timestamp": "Timestamp is the bucket start, as epoch nanoseconds.",
		},
	})
	zip.Describe("GET /v1/o11y/version", zip.Doc{
		Description: "Reports the running build: its version, whether an enterprise\nedition is present (\"N\" in this build), and whether first-user setup has\ncompleted.\n\nOpen by design; the runtime's own gate is OpenAccess.",
		Fields: map[string]string{
			"O11yVersionOut.ee":             "EE says whether an enterprise edition is present; \"N\" in this build.",
			"O11yVersionOut.setupCompleted": "SetupCompleted says whether the first user has been created.",
			"O11yVersionOut.version":        "Version is the build version.",
		},
	})
	zip.Describe("POST /v1/o11y/dependency_graph", zip.Doc{
		Description: "Returns the service dependency graph over the requested\nwindow: every parent→child edge observed, with call and error rates and\nlatency percentiles per edge.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDependency.callCount":    "CallCount is how many calls crossed the edge in the window.",
			"O11yDependency.callRate":     "CallRate is calls per second.",
			"O11yDependency.child":        "Child is the called service.",
			"O11yDependency.errorRate":    "ErrorRate is the percentage of calls that erred.",
			"O11yDependency.p50":          "P50 is the median call duration, in nanoseconds.",
			"O11yDependency.p75":          "P75 is the 75th-percentile call duration, in nanoseconds.",
			"O11yDependency.p90":          "P90 is the 90th-percentile call duration, in nanoseconds.",
			"O11yDependency.p95":          "P95 is the 95th-percentile call duration, in nanoseconds.",
			"O11yDependency.p99":          "P99 is the 99th-percentile call duration, in nanoseconds.",
			"O11yDependency.parent":       "Parent is the calling service.",
			"O11yDependencyGraphIn.end":   "End is the window end, as epoch nanoseconds. Required.",
			"O11yDependencyGraphIn.start": "Start is the window start, as epoch nanoseconds. Required.",
			"O11yDependencyGraphIn.tags":  "Tags narrow the graph to spans matching every condition.",
			"O11yTagFilter.boolValues":    "BoolValues are the values matched when the tag holds booleans.",
			"O11yTagFilter.key":           "Key is the tag to test.",
			"O11yTagFilter.numberValues":  "NumberValues are the values matched when the tag holds numbers.",
			"O11yTagFilter.operator":      "Operator is the comparison to apply — in, not_in, equals, contains and\nthe other operators the trace filter grammar names.",
			"O11yTagFilter.stringValues":  "StringValues are the values matched when the tag holds strings.",
			"O11yTagFilter.tagType":       "TagType says which kind of value the tag holds: string, number or bool.",
		},
	})
	zip.Describe("POST /v1/o11y/event", zip.Doc{
		Description: "Records one product-analytics event for the signed-in user — a track\nevent with a name and free-form attributes.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yEventIn.attributes":  "Attributes are free-form event properties.",
			"O11yEventIn.eventName":   "EventName names the event; required for track events.",
			"O11yEventIn.eventType":   "EventType is the kind of event — track, identify or group. Required.",
			"O11yEventIn.rateLimited": "RateLimited marks an event the reporting client rate-limited.",
			"O11yMessage.data":        "Data is the acknowledgment message.",
		},
	})
	zip.Describe("POST /v1/o11y/query_filter/analyze", zip.Doc{
		Description: "Analyzes a query and extracts the metric names it reads\nand the columns it groups by.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yAnalyzeIn.query":                 "Query is the query text. Required.",
			"O11yAnalyzeIn.queryType":             "QueryType says which language the query is in — promql or the datastore's\nSQL dialect. Required.",
			"O11yAnalyzeOut.data":                 "Data is the analysis.",
			"O11yAnalyzeOut.status":               "Status is \"success\".",
			"O11yColumnInfo.columnAlias":          "Alias is the column's alias in the query, when it has one.",
			"O11yColumnInfo.columnName":           "Name is the column's name.",
			"O11yQueryFilterAnalysis.groups":      "Groups are the columns the query groups by.",
			"O11yQueryFilterAnalysis.metricNames": "MetricNames are the metrics the query reads.",
		},
	})
	zip.Describe("POST /v1/o11y/register", zip.Doc{
		Description: "Creates the FIRST organization and its admin user. It is open by\ndesign — there is nobody to be signed in as yet — and refuses once setup has\ncompleted, after which new users arrive by invitation only.\n\nOpen by design; the runtime's own gate is OpenAccess.",
		Fields: map[string]string{
			"O11yRegisterIn.email":          "Email is the admin's email. Required.",
			"O11yRegisterIn.name":           "Name is the admin's display name.",
			"O11yRegisterIn.orgDisplayName": "OrgDisplayName is the organization's display name.",
			"O11yRegisterIn.orgName":        "OrgName is the organization's name.",
			"O11yRegisterIn.password":       "Password is the admin's password.",
			"O11yRegisterOut.data":          "Data is the user. The runtime answers register with the same user shape\nthe identity face reads, so it is the ONE O11yUser (identity.go) — a\ncreated user is a user, and the document names it once.",
			"O11yRegisterOut.status":        "Status is \"success\".",
			"O11yUser.createdAt":            "CreatedAt is when they joined.",
			"O11yUser.displayName":          "DisplayName is what the console shows for them.",
			"O11yUser.email":                "Email is their address.",
			"O11yUser.id":                   "ID is the user id.",
			"O11yUser.isRoot":               "IsRoot marks the org's root user, which cannot be deleted or demoted.",
			"O11yUser.orgId":                "OrgID is the org they belong to.",
			"O11yUser.status":               "Status is their lifecycle state — active, pending_invite or deleted.",
			"O11yUser.updatedAt":            "UpdatedAt is when their record last changed.",
		},
	})
	zip.Describe("POST /v1/o11y/settings/apdex", zip.Doc{
		Description: "Sets one service's apdex threshold and the status codes excluded\nfrom its score.\n\nAdmin only, as the mux tree has always gated it (AdminAccess); the runtime's\nown gate enforces it.",
		Fields: map[string]string{
			"O11yApdexSetIn.excludeStatusCodes": "ExcludeStatusCodes are status codes excluded from the score, comma\nseparated.",
			"O11yApdexSetIn.serviceName":        "ServiceName is the service the threshold applies to.",
			"O11yApdexSetIn.threshold":          "Threshold is the satisfied-response time in seconds.",
			"O11yApdexSetOut.data":              "Data is the acknowledgment.",
			"O11yApdexSetOut.status":            "Status is \"success\".",
			"O11yMessage.data":                  "Data is the acknowledgment message.",
		},
	})
	zip.Describe("POST /v1/o11y/settings/ttl", zip.Doc{
		Description: "Sets the org's retention policy for one signal: the default TTL\nin days, ordered per-label retention rules, and optional cold-storage\nsettings.\n\nAdmin only, as the mux tree has always gated it (AdminAccess); the runtime's\nown gate enforces it.",
		Fields: map[string]string{
			"O11yRetentionMatch.key":                     "Key is the label to test.",
			"O11yRetentionMatch.values":                  "Values are the label values the rule matches.",
			"O11yRetentionRule.conditions":               "Conditions all have to hold for the rule to match.",
			"O11yRetentionRule.ttlDays":                  "TTLDays is the retention applied when it does, in days.",
			"O11yRetentionSetIn.coldStorageDurationDays": "ColdStorageDurationDays is how old data must be before it moves, in days.",
			"O11yRetentionSetIn.coldStorageVolume":       "ColdStorageVolume names the volume aged data moves to, when set.",
			"O11yRetentionSetIn.defaultTTLDays":          "DefaultTTLDays is the retention for data no rule matches, in days.",
			"O11yRetentionSetIn.ttlConditions":           "TTLConditions are ordered per-label rules; the first matching rule wins.",
			"O11yRetentionSetIn.type":                    "Type is the signal the policy applies to — traces, metrics or logs.",
			"O11yRetentionSetOut.message":                "Message says what was done.",
		},
	})
	zip.Describe("POST /v1/o11y/span_percentile", zip.Doc{
		Description: "Places one span's duration among its peers: the p50/p90/p99\ndurations of like spans, and the percentile the given duration lands at.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yPercentilePosition.description":      "Description says the same in words.",
			"O11yPercentilePosition.percentile":       "Percentile is the percentile the duration lands at.",
			"O11yPercentiles.p50":                     "P50 is the median.",
			"O11yPercentiles.p90":                     "P90 is the 90th percentile.",
			"O11yPercentiles.p99":                     "P99 is the 99th percentile.",
			"O11ySpanPercentile.percentiles":          "Percentiles are the peer group's duration percentiles.",
			"O11ySpanPercentile.position":             "Position is where the given duration lands.",
			"O11ySpanPercentileIn.end":                "End is the window end, as epoch nanoseconds.",
			"O11ySpanPercentileIn.name":               "Name is the span name whose peers are compared. Required.",
			"O11ySpanPercentileIn.resourceAttributes": "ResourceAttributes narrow the peer group to spans carrying them all.",
			"O11ySpanPercentileIn.serviceName":        "ServiceName is the service the span belongs to. Required.",
			"O11ySpanPercentileIn.spanDuration":       "SpanDuration is the span's duration in nanoseconds.",
			"O11ySpanPercentileIn.start":              "Start is the window start, as epoch nanoseconds.",
			"O11ySpanPercentileOut.data":              "Data is the placement.",
			"O11ySpanPercentileOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/variables/query", zip.Doc{
		Description: "Evaluates a dashboard variable query and returns the values the\nvariable may take.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yDashboardVarValues.variableValues": "VariableValues are the values, in the order the query produced them.",
			"O11yDashboardVarsIn.query":             "Query is the variable query to evaluate. Required.",
			"O11yDashboardVarsIn.variables":         "Variables are the current values of the other dashboard variables, for\nqueries that reference them.",
			"O11yDashboardVarsOut.data":             "Data holds the values.",
			"O11yDashboardVarsOut.status":           "Status is \"success\".",
		},
	})
}
