// Code generated by zipdoc; DO NOT EDIT.
//
// The query-core face's slice of the package extraction, split into its own
// file so concurrent slices do not contend on zipdoc_gen.go; a later `go
// generate -run zipdoc ./` folds every slice back into zipdoc_gen.go, at which
// point this file is deleted.

package o11y

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/o11y/explorer/views/:viewId", zip.Doc{
		Description: "Deletes one saved explorer view by id.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11ySavedViewDeleteOut.status": "Status is \"success\".",
			"O11ySavedViewRef.viewId":       "ViewID is the view's id.",
		},
	})
	zip.Describe("GET /v1/o11y/autocomplete/aggregate_attributes", zip.Doc{
		Description: "Lists the attributes usable as an aggregate target for\nthe given telemetry and operator — what a filter builder offers after the\naggregation is chosen.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yAggregateAttributesIn.aggregateOperator": "AggregateOperator is the aggregation the attribute will be used under, e.g.\ncount, avg, sum. The runtime requires it for non-metrics sources.",
			"O11yAggregateAttributesIn.dataSource":        "DataSource is the telemetry the attributes come from — traces, logs,\nmetrics or meter. The runtime requires it.",
			"O11yAggregateAttributesIn.limit":             "Limit caps how many attributes come back. Absent means 50.",
			"O11yAggregateAttributesIn.searchText":        "SearchText narrows the attributes to those containing it.",
			"O11yAggregateAttributesOut.data":             "Data holds the attribute keys.",
			"O11yAggregateAttributesOut.status":           "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/autocomplete/attribute_keys", zip.Doc{
		Description: "Lists the attribute keys available for filtering the given\ntelemetry, each with its data type and whether it is a materialized column.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yAttributeKeysIn.aggregateAttribute": "AggregateAttribute is the metric the keys must appear on.",
			"O11yAttributeKeysIn.aggregateOperator":  "AggregateOperator is the aggregation the keys will be used under. The\nruntime requires it for non-metrics sources.",
			"O11yAttributeKeysIn.dataSource":         "DataSource is the telemetry the keys come from — traces, logs, metrics or\nmeter. The runtime requires it.",
			"O11yAttributeKeysIn.limit":              "Limit caps how many keys come back. Absent means 50.",
			"O11yAttributeKeysIn.searchText":         "SearchText narrows the keys to those containing it.",
			"O11yAttributeKeysIn.tagType":            "TagType narrows the keys to one kind — tag or resource. Empty means all;\nan invalid value reads as empty.",
			"O11yAttributeKeysOut.data":              "Data holds the attribute keys.",
			"O11yAttributeKeysOut.status":            "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/autocomplete/attribute_values", zip.Doc{
		Description: "Lists the values one attribute key has taken — string,\nnumber and bool values in their own lists — for completing a filter.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yAttributeValuesIn.aggregateAttribute":         "AggregateAttribute is the metric the values must appear on.",
			"O11yAttributeValuesIn.aggregateOperator":          "AggregateOperator is the aggregation the values will be used under. The\nruntime requires it for non-metrics sources.",
			"O11yAttributeValuesIn.attributeKey":               "AttributeKey is the key whose values to list.",
			"O11yAttributeValuesIn.dataSource":                 "DataSource is the telemetry the values come from — traces, logs or\nmetrics. The runtime requires it.",
			"O11yAttributeValuesIn.filterAttributeKeyDataType": "FilterAttributeKeyDataType is the key's data type — string, int64, float64\nor bool. Empty means unspecified.",
			"O11yAttributeValuesIn.limit":                      "Limit caps how many values come back. Absent means 50.",
			"O11yAttributeValuesIn.searchText":                 "SearchText narrows the values to those containing it.",
			"O11yAttributeValuesIn.tagType":                    "TagType narrows the search to one kind of key — tag or resource.",
			"O11yAttributeValuesOut.data":                      "Data holds the values, split by data type.",
			"O11yAttributeValuesOut.status":                    "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/explorer/views", zip.Doc{
		Description: "Lists the caller's org's saved explorer views, optionally\nnarrowed to one source page, name or category.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"CompositeQuery.fillGaps":        "FillGaps is used to fill the gaps in the time series data",
			"CompositeQuery.unit":            "Unit for the time series data shown in the graph\nThis is used in alerts to format the value and threshold",
			"O11ySavedViewListIn.category":   "Category narrows the views to one category.",
			"O11ySavedViewListIn.name":       "Name narrows the views to one name.",
			"O11ySavedViewListIn.sourcePage": "SourcePage narrows the views to one source page, e.g. traces, logs.",
			"O11ySavedViewListOut.data":      "Data holds the views.",
			"O11ySavedViewListOut.status":    "Status is \"success\".",
			"QueryEnvelope.spec":             "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":             "Type is the type of the query.",
			"SavedView.extraData":            "ExtraData is JSON encoded data used by frontend to store additional data",
		},
	})
	zip.Describe("GET /v1/o11y/explorer/views/:viewId", zip.Doc{
		Description: "Returns one saved explorer view by id.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"CompositeQuery.fillGaps": "FillGaps is used to fill the gaps in the time series data",
			"CompositeQuery.unit":     "Unit for the time series data shown in the graph\nThis is used in alerts to format the value and threshold",
			"O11ySavedViewOut.data":   "Data holds the view.",
			"O11ySavedViewOut.status": "Status is \"success\".",
			"O11ySavedViewRef.viewId": "ViewID is the view's id.",
			"QueryEnvelope.spec":      "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":      "Type is the type of the query.",
			"SavedView.extraData":     "ExtraData is JSON encoded data used by frontend to store additional data",
		},
	})
	zip.Describe("GET /v1/o11y/fields/keys", zip.Doc{
		Description: "Returns the telemetry field keys matching the selector — the\nsignal's fields grouped by name, and whether the catalog is complete.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yFieldKeysIn.endUnixMilli":    "EndUnixMilli is the window end as a unix millisecond epoch. Zero reads as\nunset.",
			"O11yFieldKeysIn.fieldContext":    "FieldContext narrows the keys to one context — resource, scope, attribute,\nspan, log or metric.",
			"O11yFieldKeysIn.fieldDataType":   "FieldDataType narrows the keys to one data type.",
			"O11yFieldKeysIn.limit":           "Limit caps how many keys come back.",
			"O11yFieldKeysIn.metricName":      "MetricName narrows the keys to those on one metric.",
			"O11yFieldKeysIn.metricNamespace": "MetricNamespace narrows the keys to one metric namespace.",
			"O11yFieldKeysIn.searchText":      "SearchText narrows the keys to those containing it.",
			"O11yFieldKeysIn.signal":          "Signal is the telemetry to read the fields of — traces, logs or metrics.",
			"O11yFieldKeysIn.source":          "Source narrows the fields to one source within the signal.",
			"O11yFieldKeysIn.startUnixMilli":  "StartUnixMilli is the window start as a unix millisecond epoch. Zero reads\nas unset.",
			"O11yFieldKeysOut.data":           "Data holds the field keys grouped by name, and whether the catalog is\ncomplete.",
			"O11yFieldKeysOut.status":         "Status is \"success\".",
			"TelemetryFieldKeySkipIndex.name": "Name is TelemetryFieldKey.Name not IndexName from Datastore",
		},
	})
	zip.Describe("GET /v1/o11y/fields/values", zip.Doc{
		Description: "Returns the values one telemetry field has taken — string, bool,\nnumber and related values — and whether the value list is complete.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yFieldValuesIn.endUnixMilli":    "EndUnixMilli is the window end as a unix millisecond epoch. Zero reads as\nunset.",
			"O11yFieldValuesIn.existingQuery":   "ExistingQuery is the query the field appears in, so related values can be\nsuggested for it.",
			"O11yFieldValuesIn.fieldContext":    "FieldContext narrows the field to one context.",
			"O11yFieldValuesIn.fieldDataType":   "FieldDataType narrows the field to one data type.",
			"O11yFieldValuesIn.limit":           "Limit caps how many values come back.",
			"O11yFieldValuesIn.metricName":      "MetricName narrows the field to one metric.",
			"O11yFieldValuesIn.metricNamespace": "MetricNamespace narrows the field to one metric namespace.",
			"O11yFieldValuesIn.name":            "Name is the field whose values to read.",
			"O11yFieldValuesIn.searchText":      "SearchText narrows the values to those containing it.",
			"O11yFieldValuesIn.signal":          "Signal is the telemetry to read the field of — traces, logs or metrics.",
			"O11yFieldValuesIn.source":          "Source narrows the field to one source within the signal.",
			"O11yFieldValuesIn.startUnixMilli":  "StartUnixMilli is the window start as a unix millisecond epoch. Zero reads\nas unset.",
			"O11yFieldValuesOut.data":           "Data holds the values by data type, and whether the value list is complete.",
			"O11yFieldValuesOut.status":         "Status is \"success\".",
		},
	})
	zip.Describe("GET /v1/o11y/query_range", zip.Doc{
		Description: "Runs a Prometheus-style range query over metrics — the\nlegacy read that predates the v5 querier — and returns the matrix, vector or\nscalar the query resolved to.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yMetricsQueryRangeIn.end":     "End is the window end, in the same form as Start, and not before it.\nRequired.",
			"O11yMetricsQueryRangeIn.query":   "Query is the PromQL expression to evaluate. Required.",
			"O11yMetricsQueryRangeIn.start":   "Start is the window start — a unix timestamp (seconds, with optional\nfraction) or an RFC 3339 time. Required.",
			"O11yMetricsQueryRangeIn.stats":   "Stats, when \"all\", asks for query statistics alongside the result.",
			"O11yMetricsQueryRangeIn.step":    "Step is the query resolution, e.g. 60s, 1m, 1h — a positive duration.\nRequired.",
			"O11yMetricsQueryRangeIn.timeout": "Timeout caps how long the query may run, e.g. 30s, 1m — a positive\nduration. Absent means the server default.",
			"O11yMetricsQueryRangeOut.data":   "Data is the result — its result type, the value, and query stats when\nasked.",
			"O11yMetricsQueryRangeOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/auto_complete/attribute_values", zip.Doc{
		Description: "Reads the attribute-value request from the body rather\nthan off the query string — the spelling the newer builder uses to send its\nfilters alongside the request.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"O11yAttributeValuesOut.data":   "Data holds the values, split by data type.",
			"O11yAttributeValuesOut.status": "Status is \"success\".",
		},
	})
	zip.Describe("POST /v1/o11y/explorer/views", zip.Doc{
		Description: "Saves a new explorer view for the caller's org and returns its\nid.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"CompositeQuery.fillGaps":       "FillGaps is used to fill the gaps in the time series data",
			"CompositeQuery.unit":           "Unit for the time series data shown in the graph\nThis is used in alerts to format the value and threshold",
			"O11ySavedViewCreateOut.data":   "Data is the new view's id.",
			"O11ySavedViewCreateOut.status": "Status is \"success\".",
			"QueryEnvelope.spec":            "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":            "Type is the type of the query.",
			"SavedView.extraData":           "ExtraData is JSON encoded data used by frontend to store additional data",
		},
	})
	zip.Describe("POST /v1/o11y/query_range", zip.Doc{
		Description: "Executes a composite query over a time range: builder\nqueries over traces, logs and metrics, formulas, trace operators, PromQL and\nDatastore SQL, answering time series, scalars or raw records as the request\ntype asks.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"CompositeQuery.queries":           "Queries is the queries to use for the request.",
			"O11yQueryRangeOut.data":           "Data is the query result — the result type, the result set, execution stats\nand any warning — as the engine rendered it.",
			"O11yQueryRangeOut.status":         "Status is \"success\".",
			"QueryEnvelope.spec":               "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":               "Type is the type of the query.",
			"QueryRangeRequest.compositeQuery": "CompositeQuery is the composite query to use for the request.",
			"QueryRangeRequest.end":            "End is the end time of the query in epoch milliseconds.",
			"QueryRangeRequest.noCache":        "NoCache is a flag to disable caching for the request.",
			"QueryRangeRequest.requestType":    "RequestType is the type of the request.",
			"QueryRangeRequest.schemaVersion":  "SchemaVersion is the version of the schema to use for the request payload.",
			"QueryRangeRequest.start":          "Start is the start time of the query in epoch milliseconds.",
			"QueryRangeRequest.variables":      "Variables is the variables to use for the request.",
		},
	})
	zip.Describe("POST /v1/o11y/query_range/format", zip.Doc{
		Description: "Parses a builder query and echoes it back normalized to the\nv3 shape — the endpoint the UI uses to canonicalize a query without running\nit.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"CompositeQuery.fillGaps":        "FillGaps is used to fill the gaps in the time series data",
			"CompositeQuery.unit":            "Unit for the time series data shown in the graph\nThis is used in alerts to format the value and threshold",
			"O11yQueryRangeFormatOut.data":   "Data is the query, normalized to the v3 shape.",
			"O11yQueryRangeFormatOut.status": "Status is \"success\".",
			"QueryEnvelope.spec":             "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":             "Type is the type of the query.",
			"QueryRangeParamsV3.step":        "step is in seconds; used for prometheus queries",
		},
	})
	zip.Describe("POST /v1/o11y/query_range/preview", zip.Doc{
		Description: "Validates a composite query and renders the Datastore\nstatements it would run WITHOUT executing it — a dry run for agentic and\ntooling use. verbose=false trades the rendered SQL and EXPLAIN for a\nlightweight per-query verdict.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"CompositeQuery.queries":                    "Queries is the queries to use for the request.",
			"O11yQueryRangePreviewIn.QueryRangeRequest": "QueryRangeRequest is the composite query to render, embedded so the request\nbody stays the bare query the execute endpoint takes.",
			"O11yQueryRangePreviewIn.verbose":           "Verbose selects the answer's depth. Empty or \"true\" renders the underlying\nDatastore SQL with EXPLAIN and granule analysis; \"false\" returns only the\nper-query valid/error/warnings verdict with no Datastore round trips.",
			"O11yQueryRangePreviewOut.data":             "Data holds one preview per query, keyed by query name — the rendered\nstatements with optional EXPLAIN and granule analysis, or the per-query\nverdict.",
			"O11yQueryRangePreviewOut.status":           "Status is \"success\".",
			"QueryEnvelope.spec":                        "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":                        "Type is the type of the query.",
			"QueryRangeRequest.compositeQuery":          "CompositeQuery is the composite query to use for the request.",
			"QueryRangeRequest.end":                     "End is the end time of the query in epoch milliseconds.",
			"QueryRangeRequest.noCache":                 "NoCache is a flag to disable caching for the request.",
			"QueryRangeRequest.requestType":             "RequestType is the type of the request.",
			"QueryRangeRequest.schemaVersion":           "SchemaVersion is the version of the schema to use for the request payload.",
			"QueryRangeRequest.start":                   "Start is the start time of the query in epoch milliseconds.",
			"QueryRangeRequest.variables":               "Variables is the variables to use for the request.",
		},
	})
	zip.Describe("POST /v1/o11y/substitute_vars", zip.Doc{
		Description: "Substitutes a query's variables and returns the\nresolved request, without running it — what a dashboard does before it\nqueries.\n\nCallers need the viewer role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"CompositeQuery.queries":           "Queries is the queries to use for the request.",
			"O11ySubstituteVarsOut.data":       "Data is the resolved composite query, with its variables substituted.",
			"O11ySubstituteVarsOut.status":     "Status is \"success\".",
			"QueryEnvelope.spec":               "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":               "Type is the type of the query.",
			"QueryRangeRequest.compositeQuery": "CompositeQuery is the composite query to use for the request.",
			"QueryRangeRequest.end":            "End is the end time of the query in epoch milliseconds.",
			"QueryRangeRequest.noCache":        "NoCache is a flag to disable caching for the request.",
			"QueryRangeRequest.requestType":    "RequestType is the type of the request.",
			"QueryRangeRequest.schemaVersion":  "SchemaVersion is the version of the schema to use for the request payload.",
			"QueryRangeRequest.start":          "Start is the start time of the query in epoch milliseconds.",
			"QueryRangeRequest.variables":      "Variables is the variables to use for the request.",
		},
	})
	zip.Describe("PUT /v1/o11y/explorer/views/:viewId", zip.Doc{
		Description: "Replaces one saved explorer view by id with the given view and\nechoes it back.\n\nCallers need the editor role; the runtime's own gate enforces it.",
		Fields: map[string]string{
			"CompositeQuery.fillGaps":         "FillGaps is used to fill the gaps in the time series data",
			"CompositeQuery.unit":             "Unit for the time series data shown in the graph\nThis is used in alerts to format the value and threshold",
			"O11ySavedViewOut.data":           "Data holds the view.",
			"O11ySavedViewOut.status":         "Status is \"success\".",
			"O11ySavedViewUpdateIn.SavedView": "SavedView is the new view content, embedded so the request body stays the\nbare view the create endpoint takes.",
			"O11ySavedViewUpdateIn.viewId":    "ViewID is the id of the view to replace, taken from the URL.",
			"QueryEnvelope.spec":              "Spec is the deferred decoding of the query if any.",
			"QueryEnvelope.type":              "Type is the type of the query.",
			"SavedView.extraData":             "ExtraData is JSON encoded data used by frontend to store additional data",
		},
	})
}
