// Code generated by zipdoc; DO NOT EDIT.

package o11y

import (
	"github.com/zap-proto/zip"
)

func init() {
	// alert rules
	zip.Describe("GET /v1/o11y/rules", zip.Doc{
		Description: "Lists all alert rules with their current evaluation state. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/rules/:id", zip.Doc{
		Description: "Returns one alert rule with its evaluation state, by id. Viewer gate.",
	})
	zip.Describe("POST /v1/o11y/rules", zip.Doc{
		Description: "Creates a new alert rule and answers with the stored rule. Editor gate.",
	})
	zip.Describe("PUT /v1/o11y/rules/:id", zip.Doc{
		Description: "Replaces an alert rule's definition, by id. Editor gate.",
	})
	zip.Describe("DELETE /v1/o11y/rules/:id", zip.Doc{
		Description: "Removes an alert rule, by id. Editor gate.",
	})
	zip.Describe("PATCH /v1/o11y/rules/:id", zip.Doc{
		Description: "Applies a partial update to an alert rule, by id, answering with the\nstored rule — the common toggle for enabling or muting a rule. Editor gate.",
	})
	zip.Describe("POST /v1/o11y/rules/test", zip.Doc{
		Description: "Fires a test notification for a rule definition without saving it,\nanswering with how many series would alert. Editor gate.",
	})

	// planned maintenance / downtime schedules
	zip.Describe("GET /v1/o11y/downtime_schedules", zip.Doc{
		Description: "Lists all planned maintenance windows, optionally narrowed to the active\nones or the recurring ones. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/downtime_schedules/:id", zip.Doc{
		Description: "Returns one planned maintenance window, by id. Viewer gate.",
	})
	zip.Describe("POST /v1/o11y/downtime_schedules", zip.Doc{
		Description: "Creates a planned maintenance window, answering with the stored\nschedule. Editor gate.",
	})
	zip.Describe("PUT /v1/o11y/downtime_schedules/:id", zip.Doc{
		Description: "Replaces a planned maintenance window, by id. Editor gate.",
	})
	zip.Describe("DELETE /v1/o11y/downtime_schedules/:id", zip.Doc{
		Description: "Removes a planned maintenance window, by id. Editor gate.",
	})

	// rule state history — v2 (GET, query parameters)
	zip.Describe("GET /v1/o11y/rules/:id/history/stats", zip.Doc{
		Description: "Returns trigger and resolution statistics for a rule over the selected\ntime range, current window against the prior one. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/rules/:id/history/timeline", zip.Doc{
		Description: "Returns paginated timeline entries for a rule's state transitions,\nfilterable by state and a label expression, cursor-paginated. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/rules/:id/history/top_contributors", zip.Doc{
		Description: "Returns the label combinations that contributed most to a rule firing\nover the selected range. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/rules/:id/history/filter_keys", zip.Doc{
		Description: "Returns the distinct label keys present in a rule's history entries over\nthe selected range, for building history filters. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/rules/:id/history/filter_values", zip.Doc{
		Description: "Returns the distinct values a given label key has taken across a rule's\nhistory entries. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/rules/:id/history/overall_status", zip.Doc{
		Description: "Returns the overall firing/inactive intervals for a rule over the\nselected range. Viewer gate.",
	})

	// rule state history — v1 (POST, JSON body) + legacy test-fire
	zip.Describe("POST /v1/o11y/testRule", zip.Doc{
		Description: "Fires a test notification for the posted rule definition and answers\nwith how many series alerted and a status message. The legacy path; prefer\n/rules/test. Editor gate.",
	})
	zip.Describe("POST /v1/o11y/rules/:id/history/stats", zip.Doc{
		Description: "Returns trigger and resolution statistics for a rule, current window\nagainst the prior one, for the posted query range. Viewer gate.",
	})
	zip.Describe("POST /v1/o11y/rules/:id/history/timeline", zip.Doc{
		Description: "Returns a rule's state-transition timeline for the posted query range,\neach entry carrying its related-logs or related-traces link. Viewer gate.",
	})
	zip.Describe("POST /v1/o11y/rules/:id/history/top_contributors", zip.Doc{
		Description: "Returns the label combinations that contributed most to a rule firing,\nfor the posted query range. Viewer gate.",
	})
	zip.Describe("POST /v1/o11y/rules/:id/history/overall_status", zip.Doc{
		Description: "Returns the overall firing/inactive windows for a rule, for the posted\nquery range. Viewer gate.",
	})

	// notification channels
	zip.Describe("GET /v1/o11y/channels", zip.Doc{
		Description: "Lists the org's notification channels. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/channels/:id", zip.Doc{
		Description: "Returns one notification channel, by id. Viewer gate.",
	})
	zip.Describe("POST /v1/o11y/channels", zip.Doc{
		Description: "Creates a notification channel, answering with the stored channel. Admin gate.",
	})
	zip.Describe("PUT /v1/o11y/channels/:id", zip.Doc{
		Description: "Replaces a notification channel's receiver, by id. Admin gate.",
	})
	zip.Describe("DELETE /v1/o11y/channels/:id", zip.Doc{
		Description: "Removes a notification channel, by id. Admin gate.",
	})
	zip.Describe("POST /v1/o11y/channels/test", zip.Doc{
		Description: "Sends a test notification to the posted receiver. Editor gate.",
	})
	zip.Describe("POST /v1/o11y/testChannel", zip.Doc{
		Description: "Sends a test notification to the posted receiver. The legacy path;\nprefer /channels/test. Editor gate.",
	})

	// route policies
	zip.Describe("GET /v1/o11y/route_policies", zip.Doc{
		Description: "Lists the org's route policies. Viewer gate.",
	})
	zip.Describe("GET /v1/o11y/route_policies/:id", zip.Doc{
		Description: "Returns one route policy, by id. Viewer gate.",
	})
	zip.Describe("POST /v1/o11y/route_policies", zip.Doc{
		Description: "Creates a route policy, answering with the stored policy. Admin gate.",
	})
	zip.Describe("PUT /v1/o11y/route_policies/:id", zip.Doc{
		Description: "Replaces a route policy, by id, answering with the stored policy. Admin gate.",
	})
	zip.Describe("DELETE /v1/o11y/route_policies/:id", zip.Doc{
		Description: "Removes a route policy, by id. Admin gate.",
	})

	// alerts
	zip.Describe("GET /v1/o11y/alerts", zip.Doc{
		Description: "Returns the org's current alerts. Viewer gate.",
	})
}
