version: "3"
x-common: &common
  networks:
    - o11y-net
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "3"
x-clickhouse-defaults: &clickhouse-defaults
  !!merge <<: *common
  image: ghcr.io/hanzoai/datastore:25.5.6
  tty: true
  labels:
    o11y.hanzo.ai/scrape: "true"
    o11y.hanzo.ai/port: "9363"
    o11y.hanzo.ai/path: "/metrics"
  depends_on:
    init-clickhouse:
      condition: service_completed_successfully
    zookeeper-1:
      condition: service_healthy
  healthcheck:
    test:
      - CMD
      - wget
      - --spider
      - -q
      - 0.0.0.0:8123/ping
    interval: 30s
    timeout: 5s
    retries: 3
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144
  environment:
    - CLICKHOUSE_SKIP_USER_SETUP=1
x-zookeeper-defaults: &zookeeper-defaults
  !!merge <<: *common
  image: ghcr.io/hanzoai/zookeeper:3.7.1
  user: root
  labels:
    o11y.hanzo.ai/scrape: "true"
    o11y.hanzo.ai/port: "9141"
    o11y.hanzo.ai/path: "/metrics"
  healthcheck:
    test:
      - CMD-SHELL
      - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
    interval: 30s
    timeout: 5s
    retries: 3
x-db-depend: &db-depend
  !!merge <<: *common
  depends_on:
    clickhouse:
      condition: service_healthy
services:
  init-clickhouse:
    !!merge <<: *common
    image: ghcr.io/hanzoai/datastore:25.5.6
    container_name: o11y-init-datastore
    command:
      - bash
      - -c
      - |
        version="v0.0.1"
        node_os=$$(uname -s | tr '[:upper:]' '[:lower:]')
        node_arch=$$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
        echo "Fetching histogram-binary for $${node_os}/$${node_arch}"
        cd /tmp
        wget -O histogram-quantile.tar.gz "https://github.com/Hanzo O11y/observe/releases/download/histogram-quantile%2F$${version}/histogram-quantile_$${node_os}_$${node_arch}.tar.gz"
        tar -xvzf histogram-quantile.tar.gz
        mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile
    restart: on-failure
    volumes:
      - ../common/clickhouse/user_scripts:/var/lib/clickhouse/user_scripts/
  zookeeper-1:
    !!merge <<: *zookeeper-defaults
    container_name: o11y-zookeeper-1
    # ports:
    #   - "2181:2181"
    #   - "2888:2888"
    #   - "3888:3888"
    volumes:
      - zookeeper-1:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141
  clickhouse:
    !!merge <<: *clickhouse-defaults
    container_name: o11y-datastore
    # ports:
    #   - "9000:9000"
    #   - "8123:8123"
    #   - "9181:9181"
    volumes:
      - ../common/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ../common/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ../common/clickhouse/custom-function.xml:/etc/clickhouse-server/custom-function.xml
      - ../common/clickhouse/user_scripts:/var/lib/clickhouse/user_scripts/
      - ../common/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - clickhouse:/var/lib/clickhouse/
      # - ../common/clickhouse/storage.xml:/etc/clickhouse-server/config.d/storage.xml
  observe:
    !!merge <<: *db-depend
    image: ghcr.io/hanzoai/o11y:${VERSION:-v0.115.0}
    container_name: observe
    ports:
      - "8080:8080" # observe port
    volumes:
      - sqlite:/var/lib/observe/
    environment:
      - HANZO_ALERTMANAGER_PROVIDER=observe
      - HANZO_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - HANZO_SQLSTORE_SQLITE_PATH=/var/lib/ghcr.io/hanzoai/o11y.db
      - HANZO_TOKENIZER_JWT_SECRET=secret
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
  otel-collector:
    !!merge <<: *db-depend
    image: ghcr.io/hanzoai/otel-collector:${OTELCOL_TAG:-v0.144.2}
    container_name: o11y-otel-collector
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /o11y-otel-collector migrate sync check &&
        /o11y-otel-collector --config=/etc/otel-collector-config.yaml --manager-config=/etc/manager-config.yaml --copy-path=/var/tmp/collector-config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ../common/observe/otel-collector-opamp-config.yaml:/etc/manager-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=observe-host,os.type=linux
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
      - HANZO_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - HANZO_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - HANZO_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - HANZO_OTEL_COLLECTOR_TIMEOUT=10m
    ports:
      # - "1777:1777"     # pprof extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
  o11y-telemetrystore-migrator:
    !!merge <<: *db-depend
    image: ghcr.io/hanzoai/otel-collector:${OTELCOL_TAG:-v0.144.2}
    container_name: o11y-telemetrystore-migrator
    environment:
      - HANZO_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - HANZO_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - HANZO_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - HANZO_OTEL_COLLECTOR_TIMEOUT=10m
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /o11y-otel-collector migrate bootstrap &&
        /o11y-otel-collector migrate sync up &&
        /o11y-otel-collector migrate async up
    restart: on-failure
networks:
  o11y-net:
    name: o11y-net
volumes:
  clickhouse:
    name: o11y-datastore
  sqlite:
    name: o11y-sqlite
  zookeeper-1:
    name: o11y-zookeeper-1
