ARG ALPINE_SHA="pass-a-valid-docker-sha-otherwise-this-will-fail"

FROM alpine@sha256:${ALPINE_SHA}
LABEL maintainer="hanzoai"
WORKDIR /root

ARG OS="linux"
ARG ARCH

RUN apk update && \
    apk add ca-certificates && \
    rm -rf /var/cache/apk/*

COPY ./target/${OS}-${ARCH}/o11y-community /root/o11y-community
COPY ./templates/email /root/templates
COPY frontend/build/ /etc/o11y/web/

RUN chmod 755 /root /root/o11y-community

ENTRYPOINT ["./o11y-community", "server"]
