// Copyright 2025 Hanzo AI Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package o11yapiserver

import (
	"net/http"
	"regexp"
	"strconv"

	"github.com/gorilla/mux"
)

// verSeg matches a O11y versioned API path, capturing the version number and the
// remainder: "/api/v3/query_range" -> ("3", "/query_range").
var verSeg = regexp.MustCompile(`^/api/v([0-9]+)(/.*)$`)

// AddVersionlessAliases registers a version-less alias /api/<rest> for every O11y
// /api/vN/<rest> route on the assembled router, so the Hanzo public contract
// /v1/o11y/<resource> (which the o11y mount maps to /api/<resource>) NEVER carries
// O11y's engine version — one /v1/, no nested /vN/.
//
// It resolves the two collision classes that make a naive flatten impossible:
//
//   - A <rest> that exists in several O11y versions (query_range in v3/v4/v5,
//     dashboards, rules, users, …) aliases to the HIGHEST version's handler —
//     forward-only, matching Hanzo's "no backwards compatibility" rule.
//   - A <rest> whose version-less path is ALREADY owned by a non-versioned route
//     (the Hanzo-native llmobs routes /api/traces, /api/observations, …) is left
//     untouched: llmobs owns its names; O11y's same-named APM route stays reachable
//     only via its explicit version.
//
// It is GENERATED by walking the router, so there is no hand-maintained map and it
// survives a wholesale re-sync to upstream O11y. Call it LAST, after every route
// (query-service + apiserver + llmobs) is registered.
func AddVersionlessAliases(router *mux.Router) error {
	type cand struct {
		version int
		handler http.Handler
		methods []string
	}
	owned := map[string]bool{} // version-less paths owned by a non-versioned route
	best := map[string]cand{}  // version-less path -> highest-version candidate

	// One walk collects everything (walk order is unspecified, so decide after).
	_ = router.Walk(func(route *mux.Route, _ *mux.Router, _ []*mux.Route) error {
		tmpl, err := route.GetPathTemplate()
		if err != nil {
			return nil // matcher-only route (headers/host); nothing to alias.
		}
		methods, _ := route.GetMethods() // nil ⇒ matches all methods.
		m := verSeg.FindStringSubmatch(tmpl)
		if m == nil {
			owned[tmpl] = true // e.g. an llmobs /api/traces — it owns this name.
			return nil
		}
		versionless := "/api" + m[2]
		ver, _ := strconv.Atoi(m[1])
		if c, ok := best[versionless]; !ok || ver > c.version {
			best[versionless] = cand{version: ver, handler: route.GetHandler(), methods: methods}
		}
		return nil
	})

	for versionless, c := range best {
		if c.handler == nil || owned[versionless] {
			continue // no handler, or an llmobs/native route already owns the name.
		}
		rt := router.Handle(versionless, c.handler)
		if len(c.methods) > 0 {
			rt.Methods(c.methods...)
		}
	}
	return nil
}
