// -------------------------------------------------------------------------
// AUTO-GENERATED FILE
// -------------------------------------------------------------------------
// This file is generated by scripts/update-registry.cjs automatically
// whenever you run 'yarn install' or 'npm install'.
//
// It forces VS Code to index these specific packages to fix auto-import
// performance issues in TypeScript 4.x.
//
// PR for reference: https://github.com/hanzoai/o11y/pull/9694
// -------------------------------------------------------------------------

import '@hanzo/ui';
import '@hanzo/ui';
import '@hanzo/ui';
import 'components/ui/callout';
import '@hanzo/ui';
import '@hanzo/ui';
import '@hanzo/ui';
import 'constants/designTokens';
import 'components/ui/dialog';
import 'components/ui/drawer';
import 'lucide-react';
import 'components/ui/input';
import '@hanzo/ui';
import '@hanzo/ui';
import '@hanzo/ui';
import '@hanzo/ui';
import '@hanzo/ui';
import 'components/ui/table';
import '@hanzo/ui';
import '@hanzo/ui';
