// -------------------------------------------------------------------------
// AUTO-GENERATED FILE
// -------------------------------------------------------------------------
// This file is generated by scripts/update-registry.cjs automatically
// whenever you run 'yarn install' or 'npm install'.
//
// It forces VS Code to index these specific packages to fix auto-import
// performance issues in TypeScript 4.x.
//
// PR for reference: https://github.com/Hanzo O11y/o11y/pull/9694
// -------------------------------------------------------------------------

import '@hanzo/o11y-badge';
import '@hanzo/o11y-button';
import '@hanzo/o11y-calendar';
import '@hanzo/o11y-callout';
import '@hanzo/o11y-checkbox';
import '@hanzo/o11y-combobox';
import '@hanzo/o11y-command';
import '@hanzo/o11y-design-tokens';
import '@hanzo/o11y-dialog';
import '@hanzo/o11y-drawer';
import '@hanzo/o11y-icons';
import '@hanzo/o11y-input';
import '@hanzo/o11y-popover';
import '@hanzo/o11y-radio-group';
import '@hanzo/o11y-resizable';
import '@hanzo/o11y-sonner';
import '@hanzo/o11y-switch';
import '@hanzo/o11y-table';
import '@hanzo/o11y-toggle-group';
import '@hanzo/o11y-tooltip';
