name: commitci

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    types:
      - labeled
  merge_group:
    types:
      - checks_requested

jobs:
  refcheck:
    if: |
      github.event_name == 'merge_group' ||
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check-no-ee
        run: |
          if [ -d "ee/" ]; then
            echo "Error: ee/ directory should not exist"
            exit 1
          fi
          if grep -R --include="*.go" 'o11y/ee/' .; then
            echo "Error: Found references to ee/ packages"
            exit 1
          fi
          echo "Clean: no ee/ references found"
